### ISSUE TITLE
Is there a variable to add subnet tags for existing VPCs ?

### ISSUE THREAD

**Issue by amitsehgal** [terraform-aws-modules/terraform-aws-eks#1005]
#  I have issues
I have been using existing VPC and usually EKS tag shared is added automatically to subnets when I use this module ? I haven't seen code for it in module. My assumption is , its done by EKS service (not sure)

Is there a variable to add additional tags to existing subnets (tag is not added while creating subnets)  like `kubernetes.io/role/elb = 1` etc ? 

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [* ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently it does not add tag by default

## If this is a bug, how to reproduce? Please include a code sample if relevant.

not a bug , just a query

## What's the expected behavior?

looking for a pattern to add additional tag. do you suggest to use label module or null resource, local executor etc ?

## Environment details

* Affected module version:
* OS:
* Terraform version:

**Comment by dpiddockcmp** [comment]
This module does not modify your VPC or subnet tags

The EKS service adds some default tags to the subnets that you pass to the subnets argument.

You will need to use other terraform resources in order to modify your subnets. See the examples that use the [vpc module](https://github.com/terraform-aws-modules/terraform-aws-vpc/) to create VPCs with tags.
