### ISSUE TITLE
Managed worker nodes disk encryption. 

### ISSUE THREAD

**Issue by abhinav5656** [terraform-aws-modules/terraform-aws-eks#1023]
Hi, 

I have deployed the eks cluster with managed worker nodes. I want to enable the encryption in the disk which is attached to worker nodes. 
In this link i did not find any attribute to enable the kms encryption for the disk. there is only disk size attribute. 
https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/node_groups

Please help.

Regards

**Comment by trastle** [comment]
Not speaking for the maintainers for this module, but this is not so much a problem with the Terraform module as a problem with EKS. The (very recent) fix for this has been to add support for Launch Templates:

* https://github.com/aws/containers-roadmap/issues/585
* https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/
* https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html

It seems there is already an issue to support Launch Templates in the TF Module here: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/979

**Comment by barryib** [comment]
Closing this since https://github.com/terraform-aws-modules/terraform-aws-eks/pull/997 is now merged and [v13.1.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v13.1.0) released. See [examples/launch_templates_with_managed_node_groups](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/launch_templates_with_managed_node_groups) for disk encryption.
