### ISSUE TITLE
Unintended update when attaching an TargetGroup to an ASG created by a worker launch template

### ISSUE THREAD

**Issue by wilkej** [terraform-aws-modules/terraform-aws-eks#1177]
# I have issues

## I'm submitting a...

* [ ] bug report
* [X] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

We use the terraform-aws-eks module for the setup of the cluster and the management for the worker launch templates. First thank you all for this incredible module.

For our ingress objects we use a combination of the kube-ingress-aws-controller and traefik. The kube-ingress-aws-controller creates the application loadbalancer and target groups and attaches the target groups to the worker groups managed by the EKS module.

With aws provider >= 3.0.0, we got the that issue that terraform wants to remove the target_group_arns from the aws_autoscaling_group resouce.

Out workaround is to enter the target_group_arns manually in the scripts like

```
    target_group_arns = [
      "arn:aws:elasticloadbalancing:eu-central-1:...:targetgroup/kube-ing-TG-..../......"
    ]
```

Unfortunately I didn't find a way how to assign the values dynamically to terraform, e.g. using a data source as I don't know the name or the arn when running the scripts. The data source for target group arns doesn't provide the possibility to select them based on tags.

From my point of view an option would be to extend the `ignore_changes        = [desired_capacity]` block by target_group_arns which would work for our use case but probably not for a lot of other users.

Do you have any other idea or would it be an option to provide a dynamic list for ignore_changes?

## If this is a bug, how to reproduce? Please include a code sample if relevant.

It should work this way

- create a new eks cluster with a worker launch template
- create an aws_alb_target_group_arn
- attach the aws_alb_target_group_arn to the worker launch template

```
resource "aws_autoscaling_attachment" "asg_attachment_bar" {
  autoscaling_group_name = module.eks.workers_asg_names[0]
  alb_target_group_arn   = aws_alb_target_group.test.arn
}
```

## What's the expected behavior?

Do not remove the target_group_arn from the autoscaling group

## Are you able to fix this problem and submit a PR? Link here if you have already.

I think I could try to write something, first I wanted to ask/discuss if there is maybe an other idea/solution I missed

## Environment details

* Affected module version: 12.2.0
* OS: Ubuntu
* Terraform version: 14.2 with aws provider > 3.0

**Comment by milijander88** [comment]
Hi all. Do we have any progress regarding this bug? 
We have  also noticed  after the upgrade of aws provider 
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.0.0, the resource `aws_autoscaling_group` was changed. 
They removed Computed property and  enable Drift detection from the aws_autoscaling_group (https://github.com/hashicorp/terraform-provider-aws/pull/14064/files)

More info here :https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/guides/version-3-upgrade.html.md

Due to these changes, we need to use the workaround that @wilkej  wrote, this for now works, but not sure what will be in case of deploying EKS from the scratch . We need to somehow enable option` ignore_changes = [load_balancers, target_group_arns]` as input parameters.

The another bug was already open for this topic :
https://github.com/hashicorp/terraform-provider-aws/issues/14540

**Comment by sys0dm1n** [comment]
I am having the same issue but with my ASG of EKS. Any idea what will be in case of deploying EKS?

**Comment by sys0dm1n** [comment]
I found a work around by removing the “aws_autoscaling_attachment” ressource and adding the Classic loadbalancer under the “worker_groups” using the “load_balancers” param.
`module "eks" {
...
worker_groups = [
    {
    ...
    load_balancers                = [aws_elb.foo.name]
    }
]
}`
