### ISSUE TITLE
Default of GP3 breaks Outpost Deploys

### ISSUE THREAD

**Issue by brylex418** [terraform-aws-modules/terraform-aws-eks#1308]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/64b3916fd07f4f9d3cc01f5b00de0138b248f18e/local.tf#L46

An Outpost only supports GP2 volumes. 

I'm open to do a PR, however any thoughts @antonbabenko How you would like it structured?

**Comment by adam-imeson** [comment]
You can work around this now by adding this to your module declaration:
```
workers_group_defaults = {
    root_volume_type              = "gp2"
  }
```
It'd be pretty neat if the module could figure out that it's dealing with an outposts subnet on the fly and default to gp2 under that condition, though.

**Comment by antonbabenko** [comment]
@adam-imeson You type faster than me :) Your solution is correct.

We try to avoid magic to identify where it works because one-day AWS will add support for `gp3` to some customers and we will have to change the code somehow to work in both cases.

It is much better to ask the user for the exact values since only the user knows the platform.

**Comment by brylex418** [comment]
Sounds good 
Gonna go ahead and close the issue.
