### ISSUE TITLE
Do managed node groups' AMI get updated automatically?

### ISSUE THREAD

**Issue by jaimehrubiks** [terraform-aws-modules/terraform-aws-eks#1466]
According to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#release_version
omitting release_version or setting to null would set the AMI to latest version.

I found that this is true for new node groups, but existing ones do not get updates when a new version of the AMI is released.
For example, in my case the version I have is 1.18.9-20210526, but the latest is 1.18.9-20210621, which is the version I get when I create a new node group.

I wonder if this is intended or not, and if we should implement a similar mechanism as what we use in workers_launch_template, such that applying terraform would always apply the latest AMI available by using a terraform data source.

**Comment by jaimehrubiks** [comment]
I found this other repo, maybe we can borrow some ideas
https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/ami.tf

**Comment by daroga0002** [comment]
by design Terraform is declaritive and rely on state. This means that if something was declared in code and created, then without any code change or in real state of resources it shouldnt update anything.


Personally I would rather stick declarative approach and want avoid unpredicted changes in node groups each time when I run a terraform.



@bryantbiggs @antonbabenko what are your thougth here?

**Comment by antonbabenko** [comment]
@jaimehrubiks Thanks for opening this issue!

Just discussed this exact issue in another place so I think, there should be 3 options:
1. `ami_release_version = "1.21.2-20210830"` - use specific one to manage version as configuration as code.
2. `ami_release_version = null` - This means that the `recommended` version (latest) will be used during creation.
3. `ami_release_version = "1.21"` or `ami_release_version = "recommended"` - This means that during `terraform plan`, we call AWS SSM to get the `release_version` argument from the latest `recommended` AMI for specified cluster version (e.g., `aws ssm get-parameters-by-path --path /aws/service/eks/optimized-ami/1.21/amazon-linux-2 --region eu-west-1`). This option is suitable for dev/test environments.

Option 1 and 2 are already implemented, but option 3 is new if anyone wants to work on it and start a PR. I will be able to work on it in 3-5 days because I need it, too.

**Comment by JacobWeyer** [comment]
Was this picked up by anybody?

**Comment by daroga0002** [comment]
If anybody from community wants to dig into this then is welcome to help

**Comment by joaolgn1985** [comment]
Hey guys, how are doing?

I have this same problem.
When I loaded my cluster in August, it loaded with the updated version from August and today with the latest version from October it doesn't update automatically. As the API is managed by AWS, I can't update when I make a plan for example. Has anyone managed to fix this?

**Comment by DmitriyStoyanov** [comment]
I guess this issue is still relevant and wait for implementation, so it should not be closed by bot.
Possible someone still can find solution to this feature?
