### ISSUE TITLE
Allow worker nodes to be created in private subnets if eks cluster has both private and public subnets

### ISSUE THREAD

**Issue by MarkFreebairn** [terraform-aws-modules/terraform-aws-eks#15]
# I have issues

## I'm submitting a

* [ ] bug report
* [x ] feature request
* [ ] support request

## What is the current behavior
Based on [this guide](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html) from aws, it is recommended that you specify both public and private subnets when creating your eks cluster, but that you only create your worker nodes in your private subnets. Current behaviour in this module will use the same subnets for creating the eks cluster as for placing the worker nodes within.

## What's the expected behavior
I believe it would be a good feature to add an additional (optional) list variable to the module called worker_subnets that will be used to create the worker nodes within. This means you can add private and public subnets to the `subnets` variable, but only add private subnets to the `worker_subnets` variable.

## Environment

* Affected module version:
* OS:
* Terraform version:

## Other relevant info
I have a branch with this feature on a fork, I will add a PR to be looked at.

**Comment by brandoconnor** [comment]
Hey @MarkFreebairn -

I like the idea and thanks kindly for opening an issue to get the conversation started. I 100% agree this use case should be covered.

From how I'm reading the docs, it sounds like the most flexible way to build and EKS cluster is to attach both public and private subnets to it. From a security standpoint, it would make sense beyond that to put all workers in the private subnet, but I think it'd be just as easy to allow any given worker group to exist in a specified subnet space.

I've looked at the PR and asked a few questions over there. With a few quick tweaks, I'll be happy to get this shipped 👍

**Comment by brandoconnor** [comment]
I don't think anything will be broken by putting workers in private subnets but I haven't tested it with a live application just yet. Please report back if you experiment with this @ozbillwang . I'm planning to move this option for workers into its own variable within the worker defaults map so users can pick which ASGs are placed where, mixing and matching as they see fit.

The implementation @MarkFreebairn has in PR currently (stalled) doesn't quite accomplish this yet but I hope to nudge it in that direction before just adding it myself outright.

**Comment by MarkFreebairn** [comment]
@brandoconnor apologies I've been really caught up recently and haven't had a chance to update this 😞 I understand what you mean with using the worker_groups map, definitely the right place for it, I will try to fix this as soon as I get a chance but that might not be until next week... If you wish to update it before that then feel free.

**Comment by brandoconnor** [comment]
Thanks for getting back to me @MarkFreebairn  and no rush. If it comes out of the recent churn, I'll update in the appropriate places. 👍

**Comment by bshelton229** [comment]
@brandoconnor would you take a PR for this? We need this feature. In our testing adding all public and private subnets to the EKS cluster primitive, and then launching the workers in the private subnets only, works the way we want; which is to say it still allows the cluster to create internet-facing load balancers in the public subnets while making sure all of our nodes are in the private subnets only. That  is typically how we configure our clusters. We make sure to tag our private subnets with `kubernetes.io/role/internal-elb` so internal elbs can be created in the right spot.

I think the implementation you mentioned here sounds great. Would that look like adding `subnet_ids` to the `worker_group_defaults` object. Probably a string of comma delimited subnet ids. If that string is empty the `subnets` variable is used, otherwise the list of subnet ids is used for that worker group? I can't remember, but I think you need to stick with flat maps in variables?

I wouldn't mind throwing that together if there isn't already other work in progress.

Thanks!

**Comment by ozbillwang** [comment]
@brandoconnor 

I did with v1.1.0 directly and assign all clusters to private subnets. I can still manage ALB/ELB in both public and private subnets within EKS, not sure what's your problem here?

**Comment by brandoconnor** [comment]
@bshelton229 - I'd definitely take a PR for this if you wanted to put that together.

**Comment by bshelton229** [comment]
@brandoconnor yep, the comma delimited string is what's in my branch. I'll open something up. I had a feeling we had to keep that a flat map.

**Comment by brandoconnor** [comment]
#61 fills the need here. Closing
