### ISSUE TITLE
[BUG] Lifecycle tags in node_group prevents nodegroup from being changed

### ISSUE THREAD

**Issue by timothyclarke** [terraform-aws-modules/terraform-aws-eks#1525]
## Description

Changing instance types in node groups requires a manual workaround because lifecycle tags are incorrect

If I try to switch an instance type eg t3.small -> t3.medium or even just adding more types I cannot apply without performing a targeted delete or simply removing the node group. 
The issue is https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf#L84 attempts to create a replacement identically named node group before removing the old one. 

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

All of these steps are performed by our CI server

## Versions
 - Terraform: 15.4
 - Provider(s):
 - Module:

## Reproduction
- Create cluster with node group
- Change the node group definition
- Attempt to apply the changes

### Code Snippet to Reproduce
```
node_groups = [
    {
        name                    = "change-me"
        capacity_type           = "SPOT"
        instance_types          = ["t3.medium"]
        max_capacity            = "2"
        min_capacity            = "1"
        desired_capacity        = "1"
        disk_size               = 20
        additional_tags = {
            project_cost_type   =   "Shared"
        }
        k8s_labels = {
            "example.com/nodetype"   = "changeme"
        }
    }
]
```
Replace `instance_types          = ["t3.medium"]` with `instance_types          = ["t3a.medium"]`  after the eks cluster has been created and attempt to re-apply  (note it plans fine)

## Expected behavior
Terraform should apply the change without requiring `terraform destroy -target ....` or similar

## Actual behavior
````
error creating EKS Node Group (example:change-me): ResourceInUseException: NodeGroup already exists with name change-me and cluster name example
RespMetadata: {
    StatusCode: 409,
    RequestID: "< removed uuid>"
,
  ClusterName: "example",
  Message_: "NodeGroup already exists with name change-me and cluster name example",
  NodegroupName: "change-me"
```

**Comment by selfieblue** [comment]
+1  we are ranning to the same issue.

**Comment by damienleger** [comment]
I don't understand why this bug is closed. And the whole argument like it's a normal behaviour and a limitation of the AWS API doesn't make sense to me.

The node group name must be unique. Because of [this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a9b84558b1abb4ca2a4dd07f571439ccfff79f9d/modules/node_groups/node_groups.tf#L101), the `create_before_destroy = true` , the module tries to create a node group name with the same name **before** delete it then it fails and that's it. **Without the `create_before_destroy = true` it will work, there is no such thing like AWS limitation here!**

I dig the history. In the first version of file, there was `create_before_destroy = true` but the node group name was unique because generated by a random_pet suffix to avoid name collision --> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/11147e9af34054c4c4576aa00938a2c65198ca5f/modules/node_groups/node_groups.tf#L4

In this PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1372 [the random_pet suffix was removed](https://github.com/barryib/terraform-aws-eks/blob/012ce2e36da2fd606139999b63c9db9cfbec5db1/modules/node_groups/node_groups.tf#L5) hence the node group name is not unique on re-creation, and since `create_before_destroy = true` has not been removed there is now this name collision bug. Once again regression, not AWS limitation.

Btw from https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#create_before_destroy
> This is an opt-in behavior because many remote object types have unique name requirements or other constraints that must be accommodated for both a new and an old object to exist concurrently. Some resource types offer special options to append a random suffix onto each object name to avoid collisions, for example. Terraform CLI cannot automatically activate such features, so you must understand the constraints for each resource type before using create_before_destroy with it.

**Comment by daroga0002** [comment]
let me analyze this again

**Comment by damienleger** [comment]
Digging a bit more I found this https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/upgrades.md#upgrade-module-to-v1700-for-managed-node-groups

> After the first apply, we recommand you to create a new node group and let the module use the node_group_name_prefix (by removing the name argument) to generate names and avoid collision during node groups re-creation if needed, because the lifce cycle is create_before_destroy = true.

I haven't try it (in my next upgrade I will) but I think there might be no name collision if using `name_prefix` instead of name --> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a9b84558b1abb4ca2a4dd07f571439ccfff79f9d/modules/node_groups/locals.tf#L35

If my understanding is correct, when using prefix_name, the node group are suffixed by an increment to avoid name collision.

**Comment by daroga0002** [comment]
I checked and in general lifecycle hook is there to avoid a downtime  for workload when you modify node groups which are using `name_prefix` which is default behaviour when you don`t pass `name` input into node_group definition.

Unfortunately lifecycle meta arguments cannot be conditional in terraform what is causing that we must choose which `issue` from two is acceptable:
1. issue described in this thread
2. causing downtime for workload running on node group each time even if there is use of `name_prefix` used.

From my side I think we must accept issue 1, as issue 2 will make this module will be not allowing for rolling updates at all.

**Comment by daroga0002** [comment]
@damienleger  thank you for putting attention on this 🥇

**Comment by damienleger** [comment]
Thank you @daroga0002 for the quick look. Yes I agree with you using `name_prefix` is the safest solution. So if I'm correct we can use (1) `name`, (2) `name_prefix` or neither of both then it (3) fallbacks to `name_prefix` logic. If I may, can you add in the doc the difference between (2) and (3)? From the tf code I must admit it's not clear to me 😕
