### ISSUE TITLE
Feat request: Destroy the EKS cluster with "terraform apply" instead of "terraform destroy"

### ISSUE THREAD

**Issue by jportasa** [terraform-aws-modules/terraform-aws-eks#1640]
Requested feature:

Right now only **terraform destroy** in the plan, deletes all resoruces that terraform-aws-eks module has created. But people use to have a terraform pipeline that does always "terraform init" and "terraform apply". So it brings us to have to run manually a terraform destroy sikpping the pipeline execution.

**Comment by pjrm** [comment]
Hi all,

I'm having some issues regarding this scenario also.
From what I understood, if we want to remove the EKS cluster, we can't remove the provider because it will be needed to destroy resources created inside the EKS cluster.

I want to implement a gitops approach and easily do this. By removing the EKS module, the terraform would remove the cluster with one PR. From what I have read, this doesn't seem possible to do. Has anyone tried to achieve this?

Maybe we can use terraform CDK for these specific use cases.

**Comment by mcanevet** [comment]
Here is my workaround:
```hcl
data "aws_eks_cluster" "cluster" {
  count = var.create_eks || contains(data.aws_eks_clusters.clusters.names, var.cluster_name) ? 1 : 0
  name = try(module.eks.cluster_id, var.cluster_name)
}

data "aws_eks_cluster_auth" "cluster" {
  count = var.create_eks || contains(data.aws_eks_clusters.clusters.names, var.cluster_name) ? 1 : 0
  name = try(module.eks.cluster_id, var.cluster_name)
}
```
This way, the datasource will be correctly configured to destroy resources that exists in the state but not anymore in the manifests.

**Comment by bryantbiggs** [comment]
Closing this for now with the latest release of v18.x. Please let me know if your issue still persists after updating to the latest version and we can revisit

**Comment by lemar5555** [comment]
Confirming that this issue still exists in v18.21.0.
So what is the solution, how to remove cluster with code in CI/CD without using destroy ?

**Comment by bryantbiggs** [comment]
`create` = `false`
