### ISSUE TITLE
drop create_eks module input

### ISSUE THREAD

**Issue by daroga0002** [terraform-aws-modules/terraform-aws-eks#1681]
## Description

Historicaly variable `create_eks` was created to allow common flow of destroying module resources without changing code base (setting `create_eks=false`). Main purpose was becuase terraform modules for long time where not allowing `count` or `for_each`.

Currently following constructions are allowed:
```
module "eks" {
  count           = var.create_eks ? 1 : 0
  source          = "terraform-aws-modules/eks/aws"

  cluster_version = "1.21"
  cluster_name    = "my-cluster"
  vpc_id          = "vpc-1234556abcdef"
  subnets         = ["subnet-abcde012", "subnet-bcde012a", "subnet-fghi345a"]

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]
}
```

I think we can deprecate input `create_eks` in module (this will be breaking change) what will simplify code base. 

@antonbabenko  @bryantbiggs  what are your thoughts here?

**Comment by antonbabenko** [comment]
Let's keep it as it is. `create_*` was added a few years ago because I have been mostly using Terragrunt and it is the easiest way to disable the module there.

We also use this pattern in all newer modules to control the subset of resources we want to create (for example, [eventbridge module](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/#conditional-creation)).
