### ISSUE TITLE
make node_groups module also for standalone usage

### ISSUE THREAD

**Issue by daroga0002** [terraform-aws-modules/terraform-aws-eks#1682]
## Description

Sub module `node_groups` should be also allow to standalone usage similar to fargate submodule. 

Example of fargate standalone execution:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/56e93d77de58f311f1d1d7051f40bf77e7b03524/examples/fargate/main.tf#L114-L174

**Comment by tsurankov** [comment]
Would be nice to have.
As an example, if I want to create a node group per AZ it is just not possible to loop through the list of subnets and use for_each to create a node group per AZ with the same parameters. I have to hardcode subnet IDs in the var.node_group definition of the parent module or transform the data in locals which also has limitations and leads to over-complication of the setup.
Currently, the node groups module depends on the parent module mainly because of the var.workers_group_defaults variable.
This module has to be either decoupled into a separate module or refined from the dependencies

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:
