### ISSUE TITLE
add-on coredns creating take to much time

### ISSUE THREAD

**Issue by boraozkan** [terraform-aws-modules/terraform-aws-eks#1765]
## Description

I am deploying cluster with dns add-on coredns and it is taking longer period
```
module.eks.aws_eks_addon.this["coredns"]: Still creating... [13m10s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [13m20s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [13m30s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [13m40s elapsed]
module.eks.aws_eks_addon.this["coredns"]: Still creating... [13m50s elapsed]

```
## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: Terraform v1.1.3

 - Provider(s):

 - Module: v18.0.4

## Expected behavior

To creating coredns add-on in a short or reasonable time range

**Comment by bryantbiggs** [comment]
this is not module related since its on the AWS side

**Comment by bryantbiggs** [comment]
how so? the addon takes a bit of time, theres nothing that can be done about it - correct?

**Comment by ClaytonOlleyNutrien** [comment]
I think if you're adding a lot of nodes, this can lead to timeouts... I find it best to only add a few nodes during cluster creation and then scale them up later.

**Comment by paul-pop** [comment]
The issue is because of a race condition as described here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1801#issuecomment-1019907905. 

One easy (but manual) way to fix is to head to the console after your node was created and joined the cluster and while Terraform is attempting to create the coredns addon and:

1. Head over to the Add-ons tab of your cluster
2. Select `coredns` and click `Edit`
3. Tick `Override existing configuration for this add-on on the cluster` and press Update

This is going to take a few seconds and it will show as Active at which moment Terraform will stop waiting and mark is as completed.
