### ISSUE TITLE
output certs

### ISSUE THREAD

**Issue by tomdavidson** [terraform-aws-modules/terraform-aws-eks#177]
# I have issues

Using the module with other providers is a bit awkward without the client cert and client key.

- https://www.terraform.io/docs/providers/helm/
- https://www.terraform.io/docs/providers/kubernetes/index.html

Unless I am just missing something.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

I create an EKS cluster with the module but then want to use the helm and k8s providers. terarform-aws-eks does not output the client key and client cert.

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes, but would like to make sure I am just not using it incorrectly

**Comment by max-rocket-internet** [comment]
Hi @tomdavidson!
There is no key because EKS uses the `aws-iam-authenticator` app. There is only the `certificate-authority-data` which is provided as an output already: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L12

So, in my experience, the process is something like this:
1. Create an EKS cluster
2. Merge the kubeconfig into your own
3. Then you can use `kubectl` like normal

Then you can use those 2 providers.

**Comment by dpiddockcmp** [comment]
You need Kubernetes client >= 1.10 to use the `aws-iam-authenticator`. 

The official Terraform kubernetes provider is ancient and can't use EKS clusters via IAM auth.

I don't know how the helm provider works but a recent standalone helm can work with EKS via IAM auth.

This module does not create classic certificate based auth

**Comment by dpiddockcmp** [comment]
Today saw the release of [1.3.0](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/CHANGELOG.md#130-october-23-2018) of the Kubernetes provider containing the 1.10 library. In theory this means that you can now use the kube config output by this module to configure the provider. I haven't had time to test this yet myself.

**Comment by tomdavidson** [comment]
Thank you for helping me understand better.
