### ISSUE TITLE
eks root module should complain/fail when wrong inputs are used

### ISSUE THREAD

**Issue by youwalther65** [terraform-aws-modules/terraform-aws-eks#1795]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When using EKS root module with self_managed_node_groups and specifying capacity_type = "SPOT" this is ignored and on-demand capacity is provided

## Describe the solution you'd like.
Either raise a warning or even better an error

## Describe alternatives you've considered.
Using use_mixed_instances_policy = true with proper config will deliver SPOT as expected

## Additional context
I am aware that this input is not mentioned in the corresponding documentation:
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/self-managed-node-group?tab=inputs
But raising a warning/error would help. In general It would be great have similar input configuration for MNG and self-MNG at least for inputs where it is possible from an AWS implementation perspective (example: create_role_arn vs. create_iam_instance_profile) and maybe even hiding some of the details/complexity of AWS.

**Comment by bryantbiggs** [comment]
we cannot control error messages and when they are shown to users; the best we can do is provide documentation and examples. 

regarding create_role_arn vs. create_iam_instance_profile - this is intentional; they are two different constructs. when using self-managed node groups, an ec2 IAM instance profile is required which the module can create for you or users can provide. There is an IAM role that backs this as well. With EKS managed node groups, the EKS managed node group service controls the instance profile and users are only able to create/manage the IAM role. So there is a clear distinction here in what is used and why - self managed node groups are exactly just that: you self manage everything. EKS managed node groups are partially managed by users and the EKS managed node group service
