### ISSUE TITLE
Allow users to pass IAM Role into self-managed-node-group module

### ISSUE THREAD

**Issue by sidewinder12s** [terraform-aws-modules/terraform-aws-eks#1856]
## Is your request related to a problem? Please describe.

Pre-v18 module used the same IAM Role for all node groups it provisioned. Is there a reason this was changed to 1 role per node group?

Using the self-managed-node-group module now provisions many different IAM Roles which you now need to manage in the aws-auth configmap which is fairly painful if you are not using the module within the larger eks module.

## Describe the solution you'd like.

Allow users to pass in an IAM role to be used by self-managed-node-group/fully managed outside the module.

## Describe alternatives you've considered.
None, it appears to just be a missing feature that the managed node group module supports.

**Comment by sidewinder12s** [comment]
Actually, is this supported by just passing in the IAM Instance Profile to the module?

Then simply manage the role/permissions outside the self-managed-node-group module?

**Comment by bryantbiggs** [comment]
Each node group (EKS managed node group, self managed node group, and Fargate profile) allows for disabling the IAM role creation and providing and IAM role/profile

Each node group creates its own IAM role in order to scope permissions to least privileges required (i.e. - users are able to create a node group for a specific task which requires more permissions than other node groups)

**Comment by sidewinder12s** [comment]
Yup, I think I missed it.
