### ISSUE TITLE
EKS aws-auth configmap

### ISSUE THREAD

**Issue by andrewhadji-michael** [terraform-aws-modules/terraform-aws-eks#1890]
Hi.

Apologise if I am being dumb or not asking in the right section.

I am looking for a way to populate the EKS aws-auth configmap.

With version 17 there was an option "map_users" to add users, groups and roles to the EKS cluster.

I have had a look at the v18 examples and havent seen anything to do this with managed node groups. I've found some examples for fargate profiles and self-managed nodes but not for managed node groups.

Has this been deprecated in version 18 of this module?

Any guidance would be appreciated.

Thanks

**Comment by bryantbiggs** [comment]
Hi @andrewhadji-michael , yes; the management of `aws-auth` has been removed from the module in v18.x. You can check the upgrade guide for more details

**Comment by bryantbiggs** [comment]
you can see various alternatives to manage the `aws-auth` in the examples https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L301-L336

closing for now

**Comment by wgj** [comment]
@bryantbiggs I think your link's highlighting got moved to an unrelated section due to more examples being added. Here's a [permalink](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/58285f37d1dfaacbf99055ed87f1be19cc39f5ad/examples/complete/main.tf#L199-L237) that I think highlights the section you were referring to.

To anyone reading this in the future, this updated link will most defininely also be wrong, but in a different way. YMMV.

**Comment by wgj** [comment]
Actually, I'm not so sure anymore. That example certainly looks like the `aws-auth` `configmap` is managed by the module.

**Comment by randych-gilad** [comment]
> yes; the management of `aws-auth` has been removed from the module in v18.x. You can check the upgrade guide for more details

This is fake news.
It is (on demand) managed by module (as of version 18.30.0).
And on external changed to aws-auth terraform passively aggressively suggests to change it to content it was originally provisioned with.
