### ISSUE TITLE
doc directory is missing

### ISSUE THREAD

**Issue by darnone** [terraform-aws-modules/terraform-aws-eks#1899]
## Description

IN v17.24.0 of the module there was a docs folder on the root.  If is missing ever since v18.0.  On the of the resources in that docs folder was a minimum privileged policy for EKS cluster creation.  Is the missing docs folder a bug? is the info inter still valid?

## Solution
Add the missing docs folder with updated content

**Comment by bryantbiggs** [comment]
hi @darnone - no, that was intentionally removed. We are trying to consciously provide ample information on how the module is designed and its usage patterns, but we do not want to document general EKS/Kubernetes issues/practices (there are many other sources for these). 

For the minimum IAM policy, this was removed due to the complexity required to maintain based on the number of different possible combinations. Instead, users can use 3rd party tools such as https://github.com/salesforce/policy_sentry for generating a list privilege policy that meets their clusters specifications
