### ISSUE TITLE
Add support for autoscaling group specific tags

### ISSUE THREAD

**Issue by dmi-clopez** [terraform-aws-modules/terraform-aws-eks#1932]
## Is your request related to a problem? Please describe.

I'm trying to configure the `cluster-autoscaler` chart on AWS EKS and I find the need to specify some ASG-only tags like:

```hcl
      tags = {
        "k8s.io/cluster-autoscaler/enabled"                   = "true"
        "k8s.io/cluster-autoscaler/eks-spot-demo-eks-cluster" = "owned"
      }
```

Currently, I need to tag all resources with the method above. It's not clean and doesn't feel very elegant.

## Describe the solution you'd like.

What I would like is a variable called `autoscaling_group_tags` that accepts the same parameter structure, but it only applies to ASGs

## Describe alternatives you've considered.

N/A

## Additional context

N/A

**Comment by bryantbiggs** [comment]
for EKS managed node groups you have to use https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group_tag

for self managed node groups you can do the same (preferred route), or add the tags in via `tags` in the node group definition block

closing since this has already been heavily discussed and answered
