### ISSUE TITLE
error in pulling iam instance profile: module.eks.worker_iam_instance_profile_arns

### ISSUE THREAD

**Issue by gfrid** [terraform-aws-modules/terraform-aws-eks#1965]
Trying to allocate module.eks.worker_iam_instance_profile_arns for SPOT OCEAN results in error
no documentation is available no output.tf sample exist

output "worker_iam_instance_profile_arns" {
  description = "Default IAM instance profile ARN for EKS worker groups"
  value       =  module.eks.worker_iam_instance_profile_arns	
}

resource "spotinst_ocean_aws" "spot_ocean_cluster" {
  name = var.cluster_name
  controller_id = var.cluster_name
  iam_instance_profile = module.eks.worker_iam_instance_profile_arns	
}

- Using previously-installed hashicorp/cloudinit v2.2.0
- Using previously-installed hashicorp/helm v2.4.1
- Using previously-installed hashicorp/random v3.1.0
- Using previously-installed spotinst/spotinst v1.68.0
- Using previously-installed hashicorp/local v2.1.0
- Using previously-installed hashicorp/null v3.1.0
- Using previously-installed hashicorp/tls v3.1.0
- Using previously-installed hashicorp/kubernetes v2.8.0
- Using previously-installed hashicorp/time v0.7.2
- Using previously-installed hashicorp/aws v3.74.3

Error: Unsupported attribute

on spot_ocean_controller.tf line 26, in output "worker_iam_instance_profile_arns":
    value       =  module.eks.worker_iam_instance_profile_arns	

This object does not have an attribute named
"worker_iam_instance_profile_arns".

**Comment by bryantbiggs** [comment]
This looks like you are using a version < v18.x and I am afraid that is no longer supported. 

Once you upgrade to v18.x, you can pull the necessary attributes similar to https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7aed57b173e0864a90e5146365041f0a93a9d7cb/outputs.tf#L184-L194

**Comment by gfrid** [comment]
i am already using it
module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "18.11.0"
}

**Comment by bryantbiggs** [comment]
without seeing your current configuration it will be hard to tell whats what

**Comment by gfrid** [comment]
variable cluster_name {}

module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "18.11.0"

  cluster_name                    = var.cluster_name
  cluster_version                 = "1.21"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true


  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  vpc_id     = "vpc-xxx"
  subnet_ids = ["subnet-xx", "subnet-xxxx"]
  

 # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = {
    ami_type               = "AL2_x86_64"
    disk_size              = 50
    instance_types         = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
  }

  eks_managed_node_groups = {
    blue = {}
    green = {
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["t3.large"]
      capacity_type  = "SPOT"
      labels = {
        Environment = "test"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }
      taints = {
        dedicated = {
          key    = "dedicated"
          value  = "gpuGroup"
          effect = "NO_SCHEDULE"
        }
      }
      tags = {
        ExtraTag = "example"
      }
    }
  }

}

data "aws_subnet_ids" "private" {
  vpc_id = "vpc-0a7d7f9f3582b6614"
}

resource "aws_ec2_tag" "private_subnet_shared" {
  for_each      = data.aws_subnet_ids.private.ids
  resource_id     = each.value
  key           = "kubernetes.io/cluster/${var.cluster_name}" 
  value         = "shared"
}
 
resource "aws_ec2_tag" "private_subnet_elb" {
  for_each      = data.aws_subnet_ids.private.ids
  resource_id     = each.value
  key           = "kubernetes.io/role/internal-elb" 
  value         = "1"
}

**Comment by bryantbiggs** [comment]
With EKS managed node groups, users do not have control over the IAM instance profile - this is something that the EKS managed node group service manages. We also do not have direct access to the IAM instance profile that is created either (through Terraform) https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#attributes-reference

I actually do not know how you can get ahold of the IAM instance profile. I was going to suggest using the data source for autoscaling groups and pass the ASG name from the EKS managed node groups output and then extract the profile from the data source but it doesn't provide that https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/autoscaling_group

Event the launch template doesn't provide access, not that I would know where to begin there either since there are at least two launch templates used per EKS managed node group https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/launch_template

You could maybe piece together a null resource with a CLI command to get this https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-instance-profiles-for-role.html but thats very brittle (wherever your Terraform runs will need to have the AWS cli installed)

I'm sorry - not sure I can help ya here. If you use self managed node groups you have direct access to the profile

**Comment by gfrid** [comment]
yes, i also thought about using null resource with aws cli to pull such info.

**Comment by bryantbiggs** [comment]
>  going to be problematic as the arn and name of role attached in randomized each EKS build, and we want to keep that way.

correct - the alternative is to use self managed node groups and you have more control, stability, and access to the instance profile created

closing for now since there is not much that we can do for this unfortunately
