### ISSUE TITLE
EKS Assume role and IAM level permissions for IAM AWS-CLI configured user

### ISSUE THREAD

**Issue by ashishjullia** [terraform-aws-modules/terraform-aws-eks#2044]
There used to be a minimum set of permissions for IAM on the following link but it not working anymore and returns a "404".
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/iam-permissions.md

Please update that and please try to add other required minimum permissions for the same.

**Comment by bryantbiggs** [comment]
We no longer maintain the permissions required for this module due to the various possibilities in terms of configuration. Instead, users are recommended to use tools that can analyze and provide a minimum set of permissions required for their configuration. AWS IAM Access Analyzer is one such tool, as well as https://github.com/iann0036/iamlive

**Comment by ashishjullia** [comment]
Thanks for replying but the problem is that "iamlive" is specifically pointing out permissions/policy when the "aws-cli" commands are being used.

In my scenario, I have a terraform config and a blank "IAM" configure for "aws-cli" for that I want to list out policies which are required to create that "eks cluster" using that "user".

I've been struggling with finding the permissions but no luck, please help me on this.

**Comment by bryantbiggs** [comment]
you can start with admin access to run `iamlive` or you can search google https://eksctl.io/usage/minimum-iam-policies/

**Comment by ashishjullia** [comment]
Thanks @bryantbiggs
