### ISSUE TITLE
create_cni_ipv6_iam_policy doesn't play nice with having two EKS clusters in the same account

### ISSUE THREAD

**Issue by meyerkev** [terraform-aws-modules/terraform-aws-eks#2131]
## Description

Specifically, we try to create the same IAM policy twice and then it bounces.  

```
│ Error: error creating IAM Policy AmazonEKS_CNI_IPv6_Policy: EntityAlreadyExists: A policy called AmazonEKS_CNI_IPv6_Policy already exists. Duplicate names are not allowed.
│ 	status code: 409, request id: 05ef8ed7-117c-4110-b093-3135d8b3fb61
│
│   with module.palolo_eks.module.eks_cluster.aws_iam_policy.cni_ipv6_policy[0],
│   on .terraform/modules/palolo_eks.eks_cluster/node_groups.tf line 38, in resource "aws_iam_policy" "cni_ipv6_policy":
│   38: resource "aws_iam_policy" "cni_ipv6_policy"
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 18.26.1

- Terraform version:
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.12.1
- Provider version(s):
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.12.1

## Reproduction Code [Required]

```
module "eks_cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.26.1"

  cluster_ip_family =  "ipv6"

  # We are using the IRSA created above for permissions
  create_cni_ipv6_iam_policy = true
}
```

I am using Workspaces with a cleared local cache.  

1. Create an EKS cluster
2. Open a new workspace
3. Create an EKS cluster with a different name

## Expected behavior

Terraform really doesn't come with if-statements so can we put a timestamp on the ipv6 policy?  I need to be able to either create 2 policies for CNI or attach one I made myself.  

## Actual behavior

When the 2nd cluster turns up, we have a name collision on the policy.

**Comment by bryantbiggs** [comment]
this is intentional to mirror what the managed CNI policy provides today https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f34670cf0bc84c42df14f64422ffda7298006fb8/modules/eks-managed-node-group/main.tf#L414

Ideally we wouldn't be creating the policy here in this module but instead just referencing the managed policy but the current policy only supports IPv4 and not IPv6. You can also create the policy yourself as well using the provided documentation which this module replicates https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html#cni-iam-role-create-ipv6-policy

The only caveat is that the policy needs to be named as the document states - `AmazonEKS_CNI_IPv6_Policy`

**Comment by bryantbiggs** [comment]
closing with information provided above
