### ISSUE TITLE
feat: Add option to enable Fargate Logging (for CloudWatch / Kinesis / OpenSearch destinations)

### ISSUE THREAD

**Issue by philicious** [terraform-aws-modules/terraform-aws-eks#2148]
## Is your request related to a problem? Please describe.
Fargate requires a special configmap to be present for logging to be enabled, see https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html

## Describe the solution you'd like.
Now that `aws-auth` can be provisioned using `kubernetes_config_map_v1_data`, likewise the `aws-logging` could be provisioned.
With a few more config options, the log-routing could be configured.

Also a IAM policy needs to be added to pod execution role then

---
What do you guys think ?

**Comment by bryantbiggs** [comment]
unfortunately, I don't plan on going any further in this module into cluster configuration. Because of the way the EKS service handles user provisioning, its necessary to provide support for the `aws-auth` configmap, but the remaining configurations are left up to users. You should be able to use the Helm, Kubernetes, or kubectl providers to provide the solution you are looking for
