### ISSUE TITLE
Error waiting for EKS Node Group to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred

### ISSUE THREAD

**Issue by mfolivas** [terraform-aws-modules/terraform-aws-eks#2226]
## Description
I have made all the changes; however, despite my best efforts, I am still getting the same error.  Sometimes, there is no error it is just in a never-ending loop.

```
error waiting for EKS Node Group (eks-bayview-dev:bayview-20220903203234016200000001) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred
```
My main class is the following:
```
provider "aws" {
  region = local.region
}

locals {
  name            = "${var.cluster_name}-${terraform.workspace}"
  cluster_version = var.cluster_version
  region          = var.region
  environment     = terraform.workspace

  tags = {
    cluster_name  = local.name
    environment   = local.environment
    BitBucket     = "bayview-asset-management"
    BitBucketRepo = "infra"
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name                    = local.name
  cluster_version                 = local.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
  enable_irsa                     = true

  create_cni_ipv6_iam_policy = true

  cluster_addons = {
    # Note: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
    }
  }
  

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  vpc_id     = var.vpc_id
  subnet_ids = var.private_subnets
  

  # You require a node group to schedule coredns which is critical for running correctly internal DNS.
  # If you want to use only fargate you must follow docs `(Optional) Update CoreDNS`
  # available under https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html

  eks_managed_node_group_defaults = {
    disk_size                  = 20
    instance_types             = ["m5.large"]
    ami_type                   = "AL2_x86_64"
    
    # We are using the IRSA created below for permissions
    # This is a better practice as well so that the nodes do not have the permission,
    # only the VPC CNI addon will have the permission
    iam_role_attach_cni_policy = true
  }

  eks_managed_node_groups = {
    bayview = {
      subnet_ids     = var.private_subnets
      min_size       = 2
      max_size       = 5
      desired_size   = 2
      instance_types = [var.instance_type]
      
      labels = {
        Example     = "managed_node_groups"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
        Environment = terraform.workspace
      }
      tags = local.tags
    }
  }

  # Fargate profiles
  # https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html
  fargate_profiles = {
    default = {
      name = "default"
      selectors = [
        {
          namespace = "bftg-backend"
          labels = {
            Application = "bftg-backend"
          }
        },
        {
          namespace = "default"
          labels = {
            WorkerType = "fargate"
          }
        }
      ]

      tags = merge(
        local.tags, 
        { 
          Profile = "default" 
        }
      )

      timeouts = {
        create = "20m"
        delete = "20m"
      }
    }

    secondary = {
      name = "secondary"
      selectors = [
        {
          namespace = "default"
          labels = {
            Environment = terraform.workspace
            GithubRepo  = "infra"
            GithubOrg   = "bayview-asset-management"
          }
        }
      ]

      # Using specific subnets instead of the subnets supplied for the cluster itself
      subnet_ids = var.private_subnets

      tags = merge(
        local.tags, 
        { 
          Profile = "secondary" 
        }
      )
    }
  }

  tags = local.tags
}

resource "aws_kms_key" "eks" {
  description             = "EKS Secret Encryption Key"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  tags = local.tags
}

module "vpc_cni_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"

  role_name             = "${local.name}-vpc_cni"
  attach_vpc_cni_policy = true
  vpc_cni_enable_ipv4   = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-node"]
    }
  }

  tags = local.tags
}

```

## Versions

- Module version [Required]: ~> 18.0

- Terraform version: 1.1.9

- Provider version(s):

## Reproduction Code [Required]

Yes, I am using workspaces

Yes, I have cleared the cached and the error still the same

terraform init
terraform plan
terraform apply

## Expected behavior

Generate a successful EKS with a eks managed nodegroup and fargate

## Actual behavior
The following error:
```
to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred
```

### Terminal Output Screenshot(s)

The application either generates the error or is constanlty

**Comment by oc-tdoron** [comment]
@mfolivas check the vpc_cni role that was created policy - i found it was missing permissions, thus causing nodes to not be added.

**Comment by mfolivas** [comment]
hmm, checking the @oc-tdoron , I have the following configuration:
```
{
    "Statement": [
        {
            "Action": [
                "ec2:UnassignPrivateIpAddresses",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DetachNetworkInterface",
                "ec2:DescribeTags",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypes",
                "ec2:DeleteNetworkInterface",
                "ec2:CreateNetworkInterface",
                "ec2:AttachNetworkInterface",
                "ec2:AssignPrivateIpAddresses"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "IPV4"
        },
        {
            "Action": "ec2:CreateTags",
            "Effect": "Allow",
            "Resource": "arn:aws:ec2:*:*:network-interface/*",
            "Sid": "CreateTags"
        }
    ],
    "Version": "2012-10-17"
}
```
I will be checking with my client and make sure that I have all access.

**Comment by MadsRC** [comment]
I think this is related to issue 1977.

Do you happen to run an "older" version of terraform-aws-eks? The reason I'm asking, and the reason I thing it's related to 1977, is that I got a very similar error message (Except I got a bit more info in the message that pointed me at the Autoscaling group created to house the EKS Node Group). Looking at the ASG, I noticed that under activity, it failed the creation of the EC2 instances because the instances have the instance tags in IMDS enabled. Having tags in the instance metadata service poses further restrictions on the allowed characters in the tags, compared to just having them as regular instance tags. Node groups deployed by EKS has some of these invalid tags applied.

historically, AWS has handled it gracefully by simply not adding those tags to the instances (see 1977), but I guess something must have changed recently on the backend to make it fail instead of... not failing...

The reason I'm asking if you use an old version of terraform-aws-eks is that I believe it used to come with `instance_metadata_tags = "enabled"` by default - I do not remember which version this was changed in. Your config does not mention `instance_metadata_tags`, so I believe it's using a default value. You can check this by looking at the ASG created in AWS after it fails, it should show if `instance metadata in tags` is enabled.

You can explicitly disable it by setting this in your node group config or default node group config

```
metadata_options = {
   instance_metadata_tags      = "disabled"
 }
```

I had it set to enabled, which is why it failed for me. Setting it to "disabled" for me fixed my problem ;)

**Comment by pburgisser** [comment]
I was able to deploy the cluster with managed nodes (version 18.29.0), 7 days after the deployment, the nodes become NotReady.
I dug a bit and found that pods aws-node were in CrashLoopBackOff with the log "Waiting IPAM-D". The logs within the pod are showing 403 when requesting an IP for ENI.
```
{"level":"error","ts":"2022-09-28T14:06:07.902Z","caller":"aws-k8s-agent/main.go:27","msg":"Initialization failure: failed to allocate one IP addresses on ENI eni-xxxxxxxxxxxx, err: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: REDACTED \n\tstatus code: 403, request id: 4e96971c-13f2-47d7-a542-879a021383f4: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: REDACTED \n\tstatus code: 403, request id: xxxxxxxxx"}
```
I added the permissions given by @mfolivas above to the VPC-CNI role which solved my issue.

**Comment by bryantbiggs** [comment]
> I added the permissions given by @mfolivas above to the VPC-CNI role which solved my issue.

There are two ways that VPC-CNI permissions can be provided and caveats for new clusters or IPv6 clusters:
- Permissions can be provided either via the node IAM role or via the VPC-CNI addon configuration
- You cannot create a new cluster with permissions passed only via the VPC-CNI because pods will never be assigned due to VPC-CNI dameonset unable to deploy due to lack of permissions on the node (chicken vs. the egg problem). If you want to avoid having these broad permissions available on the node and available for other pods to utilize, you must first provision the cluster with the permissions on the node IAM role and the VPC-CNI addon and after the VPC-CNI daemonsets deploy successfully, you can remove the permissions from the node IAM role
- For IPv4 clusters, AWS provides a managed IAM policy [`AmazonEKS_CNI_Policy`](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html), but for IPv6 they provide the required permissions and users have to create the policy. In this module, for IPv4 we use the AWS managed policy and provide an equivalent for IPv6 using the permissions provided by AWS

Hopefully that helps clarify permissions. By default, if you are creating an IPv4 based cluster, the module will attach the `AmazonEKS_CNI_Policy` AWS managed policy to the node IAM role created by the module, otherwise the cluster will not provision successfully. If you provide a custom IAM role, you will need to ensure the role has these permissions

**Comment by pburgisser** [comment]
Thanks for the clarification !
When you mention:

> * Permissions can be provided either via the node IAM role or via the VPC-CNI addon configuration

Are you referring to this addon ? https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ad6b2e2ab77d35d86028d69fea886f7148db7bb8/docs/irsa_integration.md#irsa-integration

Thanks

**Comment by bryantbiggs** [comment]
Somewhat, yes. You can create an IAM role for service accounts via https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks for the VPC-CNI which will have the necessary permissions. You can then pass that ARN into the addon config [like this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ad6b2e2ab77d35d86028d69fea886f7148db7bb8/examples/eks_managed_node_group/main.tf#L61) to have the addon use that IRSA role for permissions

So to clarify - we are not providing the AWS VPC-CNI addon since this is provided in EKS clusters by default, we are just providing IAM permissions through either the node IAM role(s) and/or the addon itself.

**Comment by pburgisser** [comment]
OK thanks.
I noticed that the variable `vpc_cni_enable_ipv4` was set to false. Wouldn't be enough though ? Would it be enough?

**Comment by bryantbiggs** [comment]
You can refer to that same example https://github.com/terraform-aws-modules/terraform-aws-eks/blob/ad6b2e2ab77d35d86028d69fea886f7148db7bb8/examples/eks_managed_node_group/main.tf#L407-L423

The `iam-role-for-service-accounts` sub-module provides policies for a number of popular K8s addons. Users need to toggle on which addon they are creating the IRSA role for in order for the correct permissions to be attached (one role definition can stamp out multiple different IRSA roles for each use case via a boolean flag)

**Comment by yamelnychuk** [comment]
Run into the same issue with the ipv4 IP family
`
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.30.2"

  cluster_name    = local.cluster_name
  cluster_version = "1.23"

  vpc_id     = var.vpc_id
  subnet_ids = var.vpc_private_subnets_ids

  cluster_ip_family = "ipv4"

  cluster_addons = {
    # Note: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts        = "OVERWRITE"
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
    }
    aws-ebs-csi-driver = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }

  node_security_group_additional_rules = {
    ingress_allow_access_from_control_plane = {
      type                          = "ingress"
      protocol                      = "tcp"
      from_port                     = 9443
      to_port                       = 9443
      source_cluster_security_group = true
      description                   = "Allow access from control plane to webhook port of AWS load balancer controller"
    }
    egress_mysql = {
      description = "Aurora connection"
      protocol    = "tcp"
      from_port   = 3306
      to_port     = 3306
      type        = "egress"
      cidr_blocks = var.database_subnets_cidr_blocks
    }
  }

  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    disk_size      = 20
    instance_types = [var.core_instance_type]

    iam_role_attach_cni_policy = true
  }

  eks_managed_node_groups = {
    default = {
      name         = "eks-${var.project_prefix}-${var.environment}"
      desired_size = var.core_instance_desired_size
      min_size     = var.core_instance_min_size
      max_size     = var.core_instance_max_size

      instance_types = [var.core_instance_type]
      capacity_type  = "ON_DEMAND"

      labels = {
        Environment = var.environment
      }

      tags = {
        Environment = var.environment
        Terraform   = "True"
      }

      update_config = {
        max_unavailable_percentage = 50
      }

      metadata_options = {
        http_endpoint               = "enabled"
        http_tokens                 = "required"
        http_put_response_hop_limit = 2
        instance_metadata_tags      = "disabled"
      }

      iam_role_additional_policies = [
        "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
        "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      ]
    }
  }

  fargate_profiles = {
    default = {
      name            = "default"
      create_iam_role = true
      selectors = [
        {
          namespace = "services"
        }
      ]
      tags = {
        Environment = var.environment
        Terraform   = "True"
        Fargate     = "True"
      }
      timeouts = {
        create = "10m"
        delete = "10m"
      }

      iam_role_additional_policies = [
        "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
        "arn:aws:iam::aws:policy/AmazonEKSServicePolicy",
        "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      ]
    }
  }

  cluster_endpoint_private_access      = true
  cluster_endpoint_public_access_cidrs = ["0.0.0.0/0"]
  cluster_endpoint_public_access       = true

  manage_aws_auth_configmap = true
  aws_auth_roles            = local.admin_role_map

  enable_irsa = true
}

module "vpc_cni_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "5.4.0"

  role_name_prefix      = "VPC-CNI-IRSA"
  attach_vpc_cni_policy = true
  vpc_cni_enable_ipv4   = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-node"]
    }
  }
}
`

**Comment by gfrid** [comment]
same issue appears with me also with EKS managed nodes: NotReady

**Comment by gfrid** [comment]
> same issue appears with me also with EKS managed nodes: NotReady i don't use metadata block and VPC CNI policy is attached to nodes i have opened AWS support ticket
> 
> in the conditions i see:
> 
> container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
> 
> ```
> ╷
> │ Error: error waiting for EKS Node Group (nginx333:blue-2022102307072746890000001f) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
> │ 	* i-0a52645ed41c3b232: NodeCreationFailure: Unhealthy nodes in the kubernetes cluster
> │ 
> │ 
> │ 
> │   with module.eks.module.eks_managed_node_group["blue"].aws_eks_node_group.this[0],
> │   on .terraform/modules/eks/modules/eks-managed-node-group/main.tf line 269, in resource "aws_eks_node_group" "this":
> │  269: resource "aws_eks_node_group" "this" {
> ```

after some tests its a DNS problem but i could not understand the problem from AWS side, the kubelet logs say that it can not resolve HOST. I switched AWS account and it works.

**Comment by timblaktu** [comment]
@gfrid could you provide some more context and detail about what you changed to fix the issue by "switching accounts"? I'm encountering the same error:

> NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

Using eks blueprints, but everything was working until I switched to using it to create a launch_template..
