### ISSUE TITLE
Module eks directly returns cluster name

### ISSUE THREAD

**Issue by moritz31** [terraform-aws-modules/terraform-aws-eks#2414]
## Description

It seems like when switching to cluster_name the name passed to the module is directly outputed and reused.
Since the cluster does not exist when running `terraform plan` the output of cluster_name should be null and therefore no issue should occure.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.5.1

- Terraform version: 1.3.7
- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.51.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]
```
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_name
}

module "eks" {
  version = "19.5.1"

  ...
}
```

Run the following with no existing cluster
```
terraform plan
```
## Expected behavior

It should refresh the state and show the plan as it worked with cluster_id.

## Actual behaviour

While doing the state refresh when running plan terraform will exit with the following error
```
│ Error: reading EKS Cluster (<CLUSTER_NAME>): couldn't find resource
```
As this error indicates the data object is trying to refresh the cluster but will fail because it does not exist.

**Comment by omallo** [comment]
I ran into the same issue when trying to upgrade from 18.x to 19.x.

Our setup relies on the fact that the `cluster_id` attribute in 18.x blocked until the cluster was ready. This is not the case for the `cluster_name` attribute in 19.x.

We use the `cluster_id` from 18.x inside data sources which must only be resolved once the cluster is ready, similar to the following:

```hcl
data "aws_eks_cluster" "this" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "this" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = try(data.aws_eks_cluster.this.endpoint, "")
  cluster_ca_certificate = try(base64decode(data.aws_eks_cluster.this.certificate_authority[0].data), "")
  token                  = try(data.aws_eks_cluster_auth.this.token, "")
}

provider "helm" {
  kubernetes {
    host                   = try(data.aws_eks_cluster.this.endpoint, "")
    cluster_ca_certificate = try(base64decode(data.aws_eks_cluster.this.certificate_authority[0].data), "")
    token                  = try(data.aws_eks_cluster_auth.this.token, "")
  }
}

provider "kubectl" {
  apply_retry_count      = 10
  host                   = try(data.aws_eks_cluster.this.endpoint, "")
  cluster_ca_certificate = try(base64decode(data.aws_eks_cluster.this.certificate_authority[0].data), "")
  load_config_file       = false
  token                  = try(data.aws_eks_cluster_auth.this.token, "")
}
```

The changes in 19.x break the above code and it's hard to find a stable solution with the new module. I know that there are approaches which avoid using the above data sources by instead getting the EKS token through the AWS CLI but this has it's own challenges and using the data sources as above has proven to be the most stable setup for us.

So, would it be possible to re-add an output to the module which blocks until the cluster is ready?

**Comment by bryantbiggs** [comment]
oy, this is sad to see

1. The token route is problematic and the Kubernetes/Helm providers state as much and recommend the `exec()` method
2. Don't re-wrap resources in data source for no reason - 

```hcl
data "aws_eks_cluster_auth" "this" {
  name = module.eks.cluster_name
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.this.token
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    token                  = data.aws_eks_cluster_auth.this.token
  }
}

provider "kubectl" {
  apply_retry_count      = 10
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  load_config_file       = false
  token                  = data.aws_eks_cluster_auth.this.token
}
```

I wish people took the time to learn the resource they are using, rather than quickly jumping to the conclusion that it is "wrong" and something should be done about it

**Comment by omallo** [comment]
@bryantbiggs , I understand what you're saying. However, I really think that I spent enough time in order to understand the problem, know what the different approaches imply, and decide for an approach which proofed to be the most robust for my setup.

Also, judging from different discussions on GH issues, many people seem to struggle with similar topics and even established projects like e.g. [terraform-aws-eks-blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints) (which you're actively contributing to) do things like ["re-wrapping resources in data sources for no reason"](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.21.0/data.tf#L5), or [explicitly depending on the `cluster_id` attribute](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.21.0/main.tf#L111), or even [adding further mechanisms for waiting for the cluster to be ready](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.21.0/data.tf#L10).

In any case, I would like to thank you for your quick feedback, that's really appreciated. I'll try to find a way to deal with the dropped functionality in version 19.x of the module.

**Comment by bryantbiggs** [comment]
@omallo does the code I provided above not work for your use case (not sure if you saw that it is different from what you provided)

**Comment by omallo** [comment]
@bryantbiggs , I've been testing today and your code which only uses the `aws_eks_cluster_auth` data source works sometimes but sometimes the token expires during the terraform apply. From what I can tell, the token is issued at the very beginning of the terraform apply which is different from before where the blocking `cluster_id` attribute prevented the data source from being evaluated too early.

I'll try to get the token through the `exec` attribute of the different providers and see how this goes.

**Comment by bryantbiggs** [comment]
You can refer to our [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0e3cb9a0afcea87e1da0c87ecc969ffb963619ea/examples/karpenter/main.tf#L10-L48) for the `exec()` method which is the method that Hashicorp recommends

```hcl
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      # This requires the awscli to be installed locally where Terraform is executed
      args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
    }
  }
}

provider "kubectl" {
  apply_retry_count      = 5
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
}
```

**Comment by FernandoMiguel** [comment]
@omallo 
> data source works sometimes but sometimes the token expires during the terraform apply.

the token provided by the data source is valid for 15 minutes.
if your apply takes longer than that, it won't work.
so you either have smaller plans, increase the parallelism, or use the auth method provided by @bryantbiggs

**Comment by mvink-guida** [comment]
Hi sharing my experiences on this.

We are using the stack with managed nodes and seeing aws-auth problems now with creating new clusters, so thats what this post is about, creating **new** clusters with managed nodes.

increasing the default parallellism from 10 to higher isn't a solution, since we have to wait for cluster creation and managed node creation that is not in our hands and takes in total more then 15 min, +- 20 min.

I agree with omallo, since the cluster_id has been removed the token is issued suddenly way to early as it seems a logical explanation. 

Still, the problems arose just for me starting on monday, suddenly the data part [ data "aws_eks_cluster" "cluster" ] that worked fine before with cluster_name is not valid anymore.

```yaml
# this first three lines broke this week on new clusters
data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_name
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```

```
2023-01-29T10:27:12+0000 [INFO] apply changes for cluster cluster1
╷
│ Error: reading EKS Cluster (cluster1): couldn't find resource
│ 
│   with module.eks.data.aws_eks_cluster.cluster,
│   on .terraform/modules/eks/main.tf line 1, in data "aws_eks_cluster" "cluster":
│    1: data "aws_eks_cluster" "cluster" {
│ 
```

[This](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2045
) is somehow related but commented with something i can not understand the idea of?

and actually i have no clue at the moment whats causing this since i tried earlier provider versions and all kind of suggested configurations.

If i use the provider exec method it doesnt work either.

If try use the [main.tf from complete examples](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf) to rule our own customizations i get the same error.
k8s provider version 2.17.0
aws provider version 4.52.0
aws cli: 2.9.19
eks module version mainly 19.5.1 / 19.6.0(last run to try no success)

`╷
│ Error: The configmap "aws-auth" does not exist
│ 
│   with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks/main.tf line 527, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  527: resource "kubernetes_config_map_v1_data" "aws_auth" {
│ 
╵`

If i try on existing stacks (module 18/19) you dont get the error, you get it when you start creating new clusters.

bringing back the module.eks.cluster_id in the output would leave us with a stable solution, but still a wild guess. but i am looking for something stable.

I have found a working solution but it needs two runs, after that you can even use the exec it will go fine, see below, but still feels we are not in control anymore. i am not a developer but some kind of wait for logic would be awesome.

```yaml
# this works in 2 runs 4 new clusters, no impact on existing.
data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```

these are my experiences, hoping i do something stupid and someone can hint on a solution that would be appreciated.

**Comment by bryantbiggs** [comment]
> bringing back the module.eks.cluster_id in the output would leave us with a stable solution, but still a wild guess. but i am looking for something stable.

It is there but it has a different meaning today. These changes aren't made randomly. Since AWS added support for creating EKS clusters on Outposts (local and extended clusters), the API has evolved and there is now an attribute called `id`. Today, you will only see a value for `id` if you create a local cluster on Outposts, but eventually the `id` will propagate to all EKS clusters. 

However, in Terraform, the `id` attribute is used differently - its a unique identifier that is essentially the key in the terraform state map for a resource. So when resources are first created, the implementer must select what attribute will be mapped to `id` to ensure that value is always unique to the resource created. When the cluster resource was first created, the cluster name was mapped to the `id` attribute

This brings us to today where we need to support both standard EKS clusters running in AWS and local clusters running on Outposts. If you ever create a local cluster on Outposts, inspect your kubeconfig. The authentication arguments are different than a standard EKS cluster. Standard EKS clusters authenticate via the iam authenticator using the cluster name, local clusters on Outposts authenticate using the cluster ID. Therefore, this module has been updated to correctly reflect these conditions and scenarios. What was previously `cluster_id` in the output is now simply `cluster_name`, and `cluster_id` is now pointed (correctly) to the `id` if one is provided by the API (local cluster on Outpost)

**Comment by bryantbiggs** [comment]
closing this issue for now unless there is more details on what needs to be addressed here
