### ISSUE TITLE
ipv6, karpenter & fargate issue

### ISSUE THREAD

**Issue by mikesplain** [terraform-aws-modules/terraform-aws-eks#2487]
## Description

In an effort to migrate towards these sets of modules and away from the blueprints modules, we're facing an issue with an IPV6 cluster, trying to utilize karpenter (with fargate for karpenter, similar to examples).

Currently, when creating the `AmazonEKS_CNI_IPv6_Policy` it looks like it is created with a [hard coded name](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/60cc6d7a14a661a6b1b6b838c42cc057ce6f87aa/node_groups.tf#L41-L79) with the hope that it would be shipped by default within AWS. 

When that policy is referenced later, it appears to be referenced as if it's an actual aws policy, rather than a policy we users are currently creating. 

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/60cc6d7a14a661a6b1b6b838c42cc057ce6f87aa/modules/karpenter/main.tf#L296-L297

Modifying the CNI policy to something like this fixes it for me:
```
  iam_role_policy_prefix = "arn:${local.partition}:iam::aws:policy"
  iam_role_policy_account_prefix = "arn:${local.partition}:iam:${local.account_id}:aws:policy"
  cni_policy             = var.cluster_ip_family == "ipv6" ? "${local.iam_role_policy_account_prefix}/AmazonEKS_CNI_IPv6_Policy" : "${local.iam_role_policy_account_prefix}/AmazonEKS_CNI_Policy"
```

However I was hoping opening up an issue I could ask 2 main things:
1) Is there a clear timeline on that policy being added to all accounts? Currently the hard coded name makes this hard for us to roll out to a multi cluster per account.
2) If there is no timeline, would you accept a PR that would allow users to add a prefix to the policy name and supply the policy to the karpenter module?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
v19.10.0

- Terraform version:
```
Terraform v1.3.9
on darwin_arm64
```
- Provider version(s):
```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.55.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```
## Reproduction Code [Required]

This was tested against the [karpenter examples folder](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/21e26e9045780ccf83cdbb0e1b6a2523602c6095/examples/karpenter/main.tf in this repo with the following changes:

```
diff --git a/examples/karpenter/main.tf b/examples/karpenter/main.tf
index 497fab7..ba93346 100644
--- a/examples/karpenter/main.tf
+++ b/examples/karpenter/main.tf
@@ -55,7 +55,7 @@ data "aws_ecrpublic_authorization_token" "token" {
 locals {
   name            = "ex-${replace(basename(path.cwd), "_", "-")}"
   cluster_version = "1.24"
-  region          = "eu-west-1"
+  region          = "us-east-2"
 
   vpc_cidr = "10.0.0.0/16"
   azs      = slice(data.aws_availability_zones.available.names, 0, 3)
@@ -72,15 +72,28 @@ locals {
 ################################################################################
 
 module "eks" {
-  source = "../.."
+  source  = "terraform-aws-modules/eks/aws"
+  version = "~> 19.10"
 
   cluster_name                   = local.name
   cluster_version                = local.cluster_version
   cluster_endpoint_public_access = true
+  cluster_ip_family              = "ipv6"
+  create_cni_ipv6_iam_policy     = true
 
   cluster_addons = {
     kube-proxy = {}
-    vpc-cni    = {}
+    vpc-cni = {
+      most_recent    = true
+      before_compute = true
+      configuration_values = jsonencode({
+        env = {
+          # Reference docs https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
+          ENABLE_PREFIX_DELEGATION = "true"
+          WARM_PREFIX_TARGET       = "1"
+        }
+      })
+    }
     coredns = {
       configuration_values = jsonencode({
         computeType = "Fargate"
@@ -109,26 +122,19 @@ module "eks" {
     },
   ]
 
-  fargate_profiles = merge(
-    { for i in range(3) :
-      "kube-system-${element(split("-", local.azs[i]), 2)}" => {
-        selectors = [
-          { namespace = "kube-system" }
-        ]
-        # We want to create a profile per AZ for high availability
-        subnet_ids = [element(module.vpc.private_subnets, i)]
-      }
-    },
-    { for i in range(3) :
-      "karpenter-${element(split("-", local.azs[i]), 2)}" => {
-        selectors = [
-          { namespace = "karpenter" }
-        ]
-        # We want to create a profile per AZ for high availability
-        subnet_ids = [element(module.vpc.private_subnets, i)]
-      }
-    },
-  )
+  fargate_profiles = {
+    karpenter = {
+      selectors = [
+        { namespace = "karpenter" }
+      ]
+    }
+    kube_system = {
+      name = "kube-system"
+      selectors = [
+        { namespace = "kube-system" }
+      ]
+    }
+  }
 
   tags = merge(local.tags, {
     # NOTE - if creating multiple security groups with this module, only tag the
@@ -143,10 +149,12 @@ module "eks" {
 ################################################################################
 
 module "karpenter" {
-  source = "../../modules/karpenter"
+  source  = "terraform-aws-modules/eks/aws//modules/karpenter"
+  version = "~> 19.10"
 
   cluster_name           = module.eks.cluster_name
   irsa_oidc_provider_arn = module.eks.oidc_provider_arn
+  cluster_ip_family      = "ipv6"
 
   tags = local.tags
 }
@@ -284,6 +292,14 @@ module "vpc" {
   single_nat_gateway   = true
   enable_dns_hostnames = true
 
+  enable_ipv6                     = true
+  assign_ipv6_address_on_creation = true
+  create_egress_only_igw          = true
+
+  public_subnet_ipv6_prefixes  = [0, 1, 2]
+  private_subnet_ipv6_prefixes = [3, 4, 5]
+  intra_subnet_ipv6_prefixes   = [6, 7, 8]
+
   enable_flow_log                      = true
   create_flow_log_cloudwatch_iam_role  = true
   create_flow_log_cloudwatch_log_group = true

```

## Expected behavior

Terraform should be able to attach the `AmazonEKS_CNI_IPv6_Policy` to a role.

## Actual behavior

Terraform is unable to attach policy to to role because of incorrect ARN
```
│ Error: attaching policy arn:aws:iam::aws:policy/AmazonEKS_CNI_IPv6_Policy to IAM Role Karpenter-ex-karpenter-20230221211156207300000006: NoSuchEntity: Policy arn:aws:iam::aws:policy/AmazonEKS_CNI_IPv6_Policy does not exist or is not attachable.
│       status code: 404, request id: 58e7a035-7174-4761-b38b-36e6768cacff
```

**Comment by bryantbiggs** [comment]
I will try to break this down as best as I can:
1. AWS currently does not provide an IPv6 equivalent managed policy like they do for IPv4. Therefore, to try to provide a similar experience in this module, we have provided the ability to create that IPv6 equivalent policy
2. Providing the policy raises some interesting debates - should it be treated like the managed policy or like a custom policy which supports all the various customization, etc. Here, we elected to go with the prior and treat it as a static resource to fill a gap - ultimately its up to users in terms of how they want to manage this policy (see next point why)
3. These policies, the CNI policies, are often shown as attached to the IAM role used by the nodegroups. When the VPC CNI daemonset starts up, it will have access to the permissions to start managing IPs, ENIs, etc. However, the VPC CNI addon does have the ability to  accept a `service_account_role_arn` (IRSA) which is the recommended path for users. Create an IRSA, attach the necessary permissions, and keep the permissions on the nodegroup IAM role to a bare minimum (since all resources running on the nodes will inherit those permissions). There is another module that we provide that supports this route both for IPv4 and IPv6 https://github.com/terraform-aws-modules/terraform-aws-iam/blob/ab21f0aa238fa6696aff98642f27611e264324d8/modules/iam-role-for-service-accounts-eks/policies.tf#L1234
4. Coming back around to Karpenter, yes you can view this as a "hardcoded" policy name, but it must be so or else users need to pass in information (which is the alternate route for the conditional). We cannot assume the name if users are able to provide an alternate name for the policy created by the root module. Again, this traces its roots back to the design intent of mirroring the behavior of the IPv4 based policy
5. Lastly, one recommendation I would suggest is to take the policy implementation provided by the module here and extract it out to stand on its own - then apply that across all of your accounts where it would be required. This takes it away from the current 1:1 relationship with each cluster and turns it into a 1:n (1 policy that can be used by n-clusters or n-IRSAs)

I did raise a feature request on the containers roadmap for this as well to see what might be possible from the AWS side in the future https://github.com/aws/containers-roadmap/issues/1843

**Comment by mikesplain** [comment]
Thanks for the fantastic response @bryantbiggs.  Using that, I was able to use the IAM module to solve the problem.  

Much appreciated. Thanks for your hard work!
