### ISSUE TITLE
on_demand_base_capacity parameter does not work

### ISSUE THREAD

**Issue by jakelevinez** [terraform-aws-modules/terraform-aws-eks#2498]
## Description

Setting on_demand_base_capacity in mixed instances policy does not work.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.10

- Terraform version: (Uncertain, latest version bundled in the gitlab tf templates)

- Provider version(s): aws 4.56.0

## Reproduction Code [Required]

```
eks_managed_node_groups = {
    blue = {

      min_size     = 1
      max_size     = 5
      desired_size = 2

      use_mixed_instances_policy = true
      mixed_instances_policy = {
        instances_distribution = {
          on_demand_base_capacity                  = 1
          on_demand_percentage_above_base_capacity = 0
          spot_allocation_strategy                 = "lowest-price"
        }
        override = [
          {
            instance_type = "t3.medium"
          },
          {
            instance_type = "t3.large"
          },
        ]
      }
    }
  }
```

terraform apply

 no
 yes

## Expected behavior

on demand base capacity for ASG to be set to 1 instead of zero

## Actual behavior

on demand base capacity for ASG is set to 0

### Terminal Output Screenshot(s)
![Screenshot 2023-03-01 at 2 23 15 PM](https://user-images.githubusercontent.com/31458570/222243127-2910501c-4062-4334-bb44-88dbc885429d.png)

**Comment by mustafa89** [comment]
i think this is only supported for self managed node groups.

**Comment by jeroenmaas** [comment]
Looks like it's not implemented in the submodule even though it is provided in main module.

(Here you can see the params given to eks-managed-node-group module)
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0f9d9fac93caf239386f47b0f117706ea78c2bec/node_groups.tf#L273

(Here there is no mention of on_demand_base_capacity or mixed_instances_policy even)
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.13.1/modules/eks-managed-node-group/main.tf


I think this is supported in AWS since after apply I can change on_demand_base_capacity in the console.
