### ISSUE TITLE
Add the ability to use different providers for resources

### ISSUE THREAD

**Issue by drmarconi** [terraform-aws-modules/terraform-aws-eks#254]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

To cater for use cases where different providers are required to build resources (in my case, a different assumed role is required to create IAM resources than my normal assumed role), please add the ability to explicitly define provider aliases to override the default provider inherited by the module.

For instance, a default provider uses assumed role "myBuilderRole" to build resources, however another provder using assumed role "myIAMRole" can be used to buid the IAM resources, by explicity passing both provider aliases in a providers module block during mdule declaration.

This could be defined as follows:

```
provider "aws" {
  alias = "builder"
  assume_role {
    role_arn = "arn:aws:iam::xxxxxxxxxxxx:role/myBuilderRole"
  }
}

provider "aws" {
  alias = "iam"
  assume_role {
    role_arn = "arn:aws:iam::xxxxxxxxxxxx:role/myIAMRole"
  }
}

module "eks" {
  source = "terraform-aws-modules/terraform-aws-eks"
  providers {
    builder = "aws.builder"
    iam = "aws.iam"
  }
}
```

This is outlined in the following [terraform documentation](https://www.terraform.io/docs/modules/usage.html#passing-providers-explicitly)

## Environment details

* Affected module version: 2.1.0
* OS: macOS Mojave 10.14.1
* Terraform version: v0.11.11

Thanks
L.

**Comment by max-rocket-internet** [comment]
Can give link me to another module in `terraform-aws-modules` that does this?

**Comment by drmarconi** [comment]
@max-rocket-internet sorry for the late reply!

Unfortunately I can't seem to find an example of this, but from reading the documentation, it sounds like providers need to be declared in the module (this allows us to pass in a provider block when calling the module, and each resource declaration requires a provider option, with a default value pointing to the default provider for the module.

I think this could get a bit messy, unless i'm mis-understanding the docs.

**Comment by max-rocket-internet** [comment]
OK cool. I'm not sure how to proceed then 😅

But I don't think your example using multiple different roles to create different types of resources is something to solve in this module.

Perhaps you should pre-create the resources outside of this module using your multi provider approach and them pass them to the worker groups.

**Comment by hobti01** [comment]
Without providers it's a bit of extra work to create clusters in [multiple regions](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances) while connecting the worker IAM roles to globally created policies.

Providers would allow the [module to be run multiple times](https://www.terraform.io/docs/modules/usage.html#multiple-instances-of-a-module):
```
provider "aws" {
  alias = "eu"
  version = "~> 1.47"
  region  = "eu-central-1"
}

provider "aws" {
  alias = "us"
  version = "~> 1.47"
  region  = "us-east-1"
}

module "eks_us" {
  source = "terraform-aws-modules/eks/aws"
  providers = {
    aws = "aws.us"
  }
  ...
}

module "eks_eu" {
  source = "terraform-aws-modules/eks/aws"
  providers = {
    aws = "aws.eu"
  }
  ...
}
```

**Comment by brandoconnor** [comment]
Hey folks -

Adding a link to the terraform docs on [provider aliases](https://www.terraform.io/docs/configuration-0-11/providers.html) to add some context.

I hadn't imagined a situation where a user would want to create a subset of resources using one provider and others using another. Feels a little weird, and generally, I think I'd opt for an architecture that doesn't rely on provider aliases wherever possible. Intuitively it feels similar to declaring 2, 3, ... many providers at the root-module level is a code-smell, but aliases of the same provider are a little less so. I can see some limited use cases where the sort of flexibility asked for here would be important.

@hobti01 - you give a good example of doing this in a limited way by assigning a provider alias for all resources. I like that somewhat more but that probably won't cover what @drmarconi is after. I think there's merit to what you're asking for @drmarconi and fortunately the number of AWS resources managed within the module, doesn't shrink or grow all that often. That's good because it's one less thing for future contributors to need to remember as an addition.

The use case seems somewhat limited but I think what you're pitching clears my bar to push it forward. Providing a variable map with defaults of `aws.default` for each `aws_*` resource within the module gives the right levers for someone wanting to override some or all of the providers as they see fit. Any objections? I'd like to see the docs/description around this variable to be as clear as possible as creating some resources with one provider of one version and other resources with another provider of another version, perhaps in a different region gives the end-user a ton of rope to hang themselves with. The combinations of configurations that won't work quickly outnumber those that will.

All that said, if you're needing this change, feel free to post the PR 👍
