### ISSUE TITLE
Launch templates force /dev/xvda as the root device

### ISSUE THREAD

**Issue by spingel** [terraform-aws-modules/terraform-aws-eks#281]
# Steps

1. Create a custom AMI that uses /dev/sda1 as the root device
2. Attempt to launch worker nodes with a larger root device

## Actual Result

The node has 2 volumes attached: /dev/xvda (100 GB) and /dev/sda1 (20 GB)

## Expected Result

The node has 1 volumes attached: /dev/sda1 (100 GB)

## Configuration

```
  worker_groups_launch_template = [
    {
      ami_id               = "${data.aws_ami.custom_ami.id}",
      root_volume_size     = "100"
    }, 
```

# Analysis

The module adds a block device mapping based on the standard Amazon provided AMI in wokers_launch_template.tf:

```
 block_device_mappings {
    device_name = "${data.aws_ami.eks_worker.root_device_name}"
...
 }
```

If an AMI with a different root device name is used an additional volume is provisioned rather than extending the size of the root volume.

* Affected module version: 2.2.1
* Terraform version: 0.11

**Comment by max-rocket-internet** [comment]
I think handling custom block device mapping in this module is way too complex so I think the best solution is to be able to define a custom `aws_launch_template` or `aws_launch_configuration` outside the module and pass this as a parameter to the worker group.

PRs welcome 😃

**Comment by max-rocket-internet** [comment]
No update so will close. Feel free to reopen. Also I added missing outputs so you should now be able to define the ASG and LT outside the module if you need custom block device mappings.

**Comment by ncrothe** [comment]
Just ran into this myself. Same situation: Using a custom AMI, I ended up with two volumes, the unchanged root volume from the AMI and an additional one. Took a while to find the reason - the default value root_block_device_name is based on a hard-coded lookup to the default amazon-provided image.
I agree any complex custom block setup might be out of scope for this module, but from what I see this just needs a smarter lookup for the default value so it actually looks at the provided AMI id instead of the default one.
At the very least I would either document this as a known limitation or maybe not do the the block device mapping instead of a wrong one.

**Comment by max-rocket-internet** [comment]
> from what I see this just needs a smarter lookup for the default value so it actually looks at the provided AMI id instead of the default one.

Sounds good for a PR 🙂
