### ISSUE TITLE
Self-managed node groups missing desired_capacity_type input variable. 

### ISSUE THREAD

**Issue by herrbpl** [terraform-aws-modules/terraform-aws-eks#2876]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: v4.49.0 - https://github.com/hashicorp/terraform-provider-aws/milestone/292?closed=1

## Is your request related to a problem? Please describe.

When used with aws provider 4.67.0, omitting this parameter gives on occasion: 
```log
│ Error: updating Auto Scaling Group (mygroup-2023041010452696410000007e): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, UpdateAutoScalingGroupInput.DesiredCapacityType.
```
Issue appears when you do manually change AWS ASG desired nodes configuration in console for ad-hoc operation. 
But when specifying this parameter manually in terraform module source, it causes forever drift when v4.67.0 is used.

## Describe the solution you'd like.
I would still like an option to specify this parameter value for self-managed node group

## Describe alternatives you've considered.
- For time-being workaround, added in self-managed-node-group main.tf:
```hcl
resource "aws_autoscaling_group" "this" {
 ...
  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      desired_capacity, desired_capacity_type
    ]
  }
 ...
}
```
- Thinking about ditching ASG based nodegroups entirely and move to Karpenter

## Additional context
Since some of our other modules specify currently AWS provider dependency ~4.0, I cannot yet test this with AWS 5.x providers.

**Comment by bryantbiggs** [comment]
> Thinking about ditching ASG based nodegroups entirely and move to Karpenter

This would be my recommendation, it does an amazing job managing your data plane compute and not just scaling - the overall lifecycle, making upgrades easier, etc. 

Otherwise, you will want to look at https://github.com/bryantbiggs/eks-desired-size-hack for details on the desired capacity issue and one hacky work around

**Comment by codeeno** [comment]
I have run into this issue as well. What has happened for us:

- We set up a node group using only the self-managed-node-group sub-module
- The configuration included a `schedule` definition
- Re-applying the node-group worked without issues
- When trying to re-apply the next day, terraform now wants to set `desired_capacity_type` from `units` to `null`. I am guessing something about the nightly scale-down has caused drift in an unexpected way.

```text
Error: updating Auto Scaling Group (xxx-xxxxxxxxxxxx): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, UpdateAutoScalingGroupInput.DesiredCapacityType.
```

The setup for `schedules`:
```hcl
    schedules = {
      scale-up = {
        min_size     = 1
        max_size     = "-1" # Retains current max size
        desired_size = 1
        time_zone    = "Europe/Berlin"
        recurrence   = "0 7 * * 1,2,3,4,5"
      },
      scale-down = {
        min_size     = 0
        max_size     = "-1" # Retains current max size
        desired_size = 0
        time_zone    = "Europe/Berlin"
        recurrence   = "0 21 * * 1,2,3,4,5"
      }
    }
```

I am not sure how the hack can help with this. It's not about that the `desired_size` being ignored by default, it's about Terraform wanting to change a field to null which can not be changed to null due to some weird drift issue.

As mentioned, setting the `desired_capacity_type` value to `units` explicitly helps in terms of being able to run the apply successfully, but the drift remains. How about adding desired_capacity_type to the ignored changes?
