### ISSUE TITLE
When triggering replacement of EKS Cluster, i get "Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused"

### ISSUE THREAD

**Issue by remixtj** [terraform-aws-modules/terraform-aws-eks#2918]
## Description
I've a cluster deployed using v19.21.0 of EKS module. The colleague of mine assigned me a new network to use as Service IPv4 Range, so i'm adding the new parameter `cluster_service_ipv4_cidr`.

Running apply triggers the replacement of the entire cluster:

```
Plan: 6 to add, 3 to change, 6 to destroy.
```

This is what i'm expecting.
What i'm not expecting is to have this error, blocking the possibility to run the apply:
```
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks/main.tf line 562, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  562: resource "kubernetes_config_map_v1_data" "aws_auth" {
│ 
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.21.0

- Terraform version:
```
Terraform v1.7.2
on linux_amd64
```
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.35.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.2
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]
My kubernetes provider is configured this way:

```
data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_name
}

#------------------------
#Provider kubernetes
#The Kubernetes (K8S) provider is used to interact with the resources supported by Kubernetes. The provider needs to be configured with the proper credentials before it can be used.
#Doc https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs
#------------------------
provider "kubernetes" {
  host = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
}
```

EKS module instead is default configuration + `manage_aws_auth_config_map = true`

1. configure kubernetes provider like specified in reproduction code
2. create a cluster with eks module setting default value for `cluster_service_ipv4_cidr` and `manage_aws_auth_configmap = true`
3. change `cluster_service_ipv4_cidr` value and run apply again

## Expected behavior

Have cluster resources replaced with new ones

## Actual behavior

Apply is blocked by an error about the connection to kubernetes:

```
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks/main.tf line 562, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  562: resource "kubernetes_config_map_v1_data" "aws_auth" {
│ 
```

### Workaround

The only option to proceed with the apply is:

```
terraform state rm 'module.eks.kubernetes_config_map_v1_data.aws_auth[0]'
```

**Comment by bryantbiggs** [comment]
thats because of self-referencing values, namely in the Kubernetes provider. you are replacing a cluster while your provider is pointed at a cluster that is no longer available. you should destroy the cluster and re-provision. alternatively, if you upgrade to v20 (looks like a good time since the cluster is being destroyed anyways), the removal of the `aws-auth` ConfigMap will help alleviate situations like this

**Comment by jtgorny** [comment]
I'm running into something similar using terraform-aws-eks `19.21.0`. I have an EKS cluster running `1.27`. When I want to upgrade to `1.28`, I'm getting an error on all resources referencing the kubernetes provider, including the aws-auth configmap. The errors all match this pattern:
```
 Get "http://localhost/blah/blah": dial tcp [::1]:80: connect: connection refused
```

The rbac & storage class resources I'm creating have an explicit dependency on the `module.EKS.cluster_endpoint` which shouldn't actually change during an EKS version upgrade. My provider definition looks much like OP's. I'm wondering if it's because these are being created in the same layer as the EKS cluster itself.

Example resource definition that results in connection refused:
```
resource "kubernetes_storage_class" "gp3_storage_class" {
  depends_on = [
    module.EKS.cluster_endpoint
  ]
  metadata {
    name = "gp3"
  }
  storage_provisioner = "ebs.csi.aws.com"
  reclaim_policy      = "Delete"
  volume_binding_mode = "WaitForFirstConsumer"
  parameters = {
    type   = "gp3"
    fsType = "ext4"
  }
}
```
