### ISSUE TITLE
Add option to overwrite (or importing current one) access entry.

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [terraform-aws-modules/terraform-aws-eks#2933]
## Is your request related to a new offering from AWS?
partially

## Is your request related to a problem? Please describe.
On the road to the latest version, from 19 to 20.+ there were some small steps done. 
at some point module created access point for runner. And now it is not possible to use latest versions for module, as it can't use already created role. 

```
│ Error: creating EKS Access Entry (prj:arn:aws:iam::<<ID>>:role/github-runner): operation error EKS: CreateAccessEntry, https response error StatusCode: 409, RequestID: 3378c596-fb49-4cee-bc32-31ffdea9056f, ResourceInUseException: The specified access entry resource is already in use on this cluster.
│ 
│   with module.eks.aws_eks_access_entry.this["cluster_creator_admin"],
│   on .terraform/modules/eks/main.tf line 191, in resource "aws_eks_access_entry" "this":
│  191: resource "aws_eks_access_entry" "this" {
│ 
╵
Error: Process completed with exit code 1.
```

## Describe the solution you'd like.
Would be good to have option to import current access entry. 

## Describe alternatives you've considered.
atm i manually added record in tfstate (which is strongly not recommended), and it worked well.

**Comment by bryantbiggs** [comment]
you can use https://developer.hashicorp.com/terraform/language/import

**Comment by aoggz** [comment]
We're running into the same issue. Simply using `terraform import` is not ideal and not a complete solution - we need something that will work for new and existing clusters created by this module. 

We have a company-standard terraform module containing this one. We are creating clusters everyday and maintaining existing clusters with this same module. For existing clusters, we _could_ just set `authenticationMode` to `API_AND_CONFIGMAP` with no `access_entries` and let the EKS API set the two default access entries for cluster creator and worker nodes. This is what EKS automatically does when making this transition. Because of this, we cannot use the `import` block because those resources don't exist when starting a `terraform apply`.

So when we have an access entry defined (either manually or via the `enable_cluster_creator_admin_permissions` property), this has to be a multi-step operation with the first one resulting in failure:

1. Upgrade the module w/ new EKS Access Entries
2. Run `terraform apply`, fully expecting it to fail with the error mentioned in this thread.
3. Run `terraform import`, as prescribed.
4. Re-run `terraform apply` to complete the operation.

Another option could be manually going through the clusters and running:
```sh
aws eks update-cluster-config \
   --name <CLUSTER_NAME> \
   --access-config authenticationMode=API_AND_CONFIG_MAP
```
before running `terraform apply`. Coupled with the addition of a `import` block in the module, this could avoid running into the error.

I think this will be our game plan. Thank you @yaroslav-nakonechnikov for raising this issue! This helped me think through this problem better 😄

**Comment by bryantbiggs** [comment]
> Because of this, we cannot use the import block because those resources don't exist when starting a terraform apply

which is exactly why we cannot support it in this module

> we need something that will work for new and existing clusters created by this module

I am open to thoughts, but I cannot do anything about resources created outside of this module. I don't know when they will or will not exist, I don't know what they will be named or what users will name their resources - its an unknown of unknowns problem

Have you seen the upgrade guide? If you followed the upgrade guide, you still have a multi-part process but without errors. Using https://github.com/clowdhaus/terraform-aws-eks-migrate-v19-to-v20 which was created specifically for aiding in the upgrade process will avoid the apply error you listed above in step 2

**Comment by yaroslav-nakonechnikov** [comment]
@bryantbiggs  https://github.com/clowdhaus/terraform-aws-eks-migrate-v19-to-v20 mentioned only ones, with a note to have terraform 1.7+. 
so it can't be used by all, and looks like a workaround. 


still, i'd lile to see option, which won't force adding/removing access entries. 
not all using single runner to run terraform deploy, so there is a possibility to utilize different roles. 
and atm it looks like each role will be overriden by others.  
Would be good if i'm wrong, so keeping process of upgrading further.

**Comment by bryantbiggs** [comment]
I think you need to familiarized yourself with how EKS provided access to clusters prior to cluster access entry, and what EKS is doing when you opt into cluster access entry on those clusters

**Comment by aoggz** [comment]
@bryantbiggs thanks for your thoughts on all this! I had not seen your upgrade guide, only the changelog in this repo. Thank you for pointing that out.

**Comment by bryantbiggs** [comment]
just to be clear, this is the upgrade guide which we store under the `docs/` directory https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-20.0.md

in there, it refers to this one off repo used to aid in migrating from v19 to v20
