### ISSUE TITLE
EKS Fargate Pods Unable to Access kube-dns in Managed Node Group Due to Missing DNS UDP Rule in Node Security Group

### ISSUE THREAD

**Issue by grapestore** [terraform-aws-modules/terraform-aws-eks#2990]
## Description

I have deployed the pods in the kube-system namespace on managed nodes and separated the kubernetes-dashboard pods into a different namespace to run them on Fargate.

## Versions

- Module version [20.8.3]:

- Terraform version:
```
Terraform v1.4.5
```
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.40.0
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.27.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

## Reproduction Code [Required]

```
## Setup EKS Cluster
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "20.8.3"

  cluster_name = "eks-${local.env}"
  cluster_version = "1.28"

  cluster_endpoint_public_access = true

  cluster_addons = {
    coredns = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
  }

  vpc_id                   = data.tfe_outputs.network.values.vpc_id
  subnet_ids               = data.tfe_outputs.network.values.private_subnets
  control_plane_subnet_ids = data.tfe_outputs.network.values.public_subnets
  fargate_profiles = {
    kubernetes_dashboard = {
      subnet_ids = data.tfe_outputs.network.values.private_subnets
      selectors = [
        {
          namespace = "kubernetes-dashboard"
        }
      ]
    }
  }
  eks_managed_node_group_defaults = {
    instance_types = ["t3.medium", "m5.large"]
  }


  eks_managed_node_groups = {
    core_system = {
      desired_capacity = 2
      max_capacity     = 3
      min_capacity     = 1
      instance_types   = ["t3.medium"]
    }
  }

  enable_cluster_creator_admin_permissions = false

  access_entries = {
    terraform_manager = {
      principal_arn = "arn:aws:iam::xxxxxxxxxxxx:user/terraform-dev"
      type          = "STANDARD"
      policy_associations = {
        admin = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          access_scope = {
            type = "cluster"
          }
        }
      }
    }
  }
}

```

## Expected behavior

The pods running on Fargate were unable to query pods in a different namespace. So, I deployed dnsutils on Fargate to try an nslookup, but the following error occurred.

## Actual behavior

Fargate pods also need to have access to the kube-dns located in the managed node group.

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-eks/assets/87048860/706b4024-d3c4-41a4-87a7-d90a19bc95d6)

## Additional context

I understood that Fargate pods inherit the cluster's primary security group, but the issue occurred because the node security group ingress rule did not have the cluster's primary security group DNS UDP rule set.

It seems that Fargate does not use the security group that is created in the Terraform module and attached to the cluster.
The issue was resolved by adding the following code.
```
data "aws_eks_cluster" "eks_cluster" {
  name = module.eks.cluster_name
}

resource "aws_security_group_rule" "fargate_to_node_dns_udp" {
  security_group_id        = module.eks.node_security_group_id
  type                     = "ingress"
  from_port                = 53
  to_port                  = 53
  protocol                 = "udp"
  source_security_group_id = data.aws_eks_cluster.eks_cluster.vpc_config[0].cluster_security_group_id
}
```

**Comment by grapestore** [comment]
In my opinion, I think creating a new security group for security purposes and attaching it to the cluster is a great idea! However, attaching a custom security group for Fargate doesn't seem easy and appears to be difficult to handle. I think it would be helpful to provide examples or how about adding an ingress rule for the primary security group to the security group of the node group? It seems difficult to debug otherwise.

**Comment by bryantbiggs** [comment]
I don't quite follow - users do not have control over the security group used by EKS Fargate, the service manages that and you don't have any options there. 

In terms of overall security group rules/access, we can't anticipate every scenario - we have provided a "sane" set of limited rules, with the default option of commonly used rules, in order to balance security guidance of least access with usability. However, as per our docs, its up to users to ensure the appropriate access is enabled based on their configuration, architecture, and applications in use

**Comment by iamnicolasvdb** [comment]
We also had this problem when running core-dns in Fargate as we migrated to a scale-to-zero scenario where we run Core-DNS, Karpenter and kube-downscaler on Fargate and had no managed nodes anymore in the cluster. We would rely on Karpenter to scale nodes for our environment. Anyhow we also worked around this issue likewise grapestore mentioned.

As in the documentation here: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html
 _Make sure that Pods on these nodes can communicate freely with the Pods that are running on Fargate. Pods that are running on Fargate are automatically configured to use the cluster security group for the cluster that they're associated with. Ensure that any existing nodes in your cluster can send and receive traffic to and from the cluster security group._
 
This is excluded from the addition security group added to the cluster, only the cluster security group gets attached.
We used this external resources to solve this issue.

```
resource "aws_security_group_rule" "ingress_coredns_fargate_port_tcp" {
  description              = "CoreDNS Fargate dns query"   
  type                     = "ingress"
  from_port                = 53
  to_port                  = 53
  protocol                 = "tcp"
  source_security_group_id = module.eks.node_security_group_id
  security_group_id        = module.eks.cluster_primary_security_group_id
}

resource "aws_security_group_rule" "ingress_coredns_fargate_port_udp" {
  description              = "CoreDNS Fargate dns query"
  type                     = "ingress"
  from_port                = 53
  to_port                  = 53
  protocol                 = "udp"
  source_security_group_id = module.eks.node_security_group_id
  security_group_id        = module.eks.cluster_primary_security_group_id
}
```

There is another workaround however that we tested but didn't used because of limitations. You could use Security Groups for Pods where you could assign different Security Groups per Pod running on the cluster. But this is limited to following EC2 types as per documentation
_Security groups for Pods are supported by most [Nitro-based](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances) Amazon EC2 instance families, though not by all generations of a family. For example, the m5, c5, r5, p3, m6g, c6g, and r6g instance family and generations are supported. No instance types in the t family are supported._ 
And as you enable this feature cluster wide, you are limited in using only these instance types.
https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html

This was done, just for reference for anyone asking with following code (and enabling this feature on the vpc-cni add-on):

```
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  podSelector: 
    matchLabels:
%{ for match_labels_key, match_labels_value in match_labels }
      ${match_labels_key} : ${match_labels_value}
%{ endfor ~}
  securityGroups:
    groupIds:
      - ${security_group_id}
      
resource "kubectl_manifest" "coredns_pod_securitygroup" {
  yaml_body = templatefile("${path.module}/files/pod-securitygroup.yml", {
    name              = "coredns"
    namespace         = "kube-system"
    security_group_id = module.eks.node_security_group_id
    match_labels = {
      k8s-app = "kube-dns"
    }
  })
}
```
