### ISSUE TITLE
Support for mixed instance types in one worker fleet

### ISSUE THREAD

**Issue by rverma-nikiai** [terraform-aws-modules/terraform-aws-eks#300]
# I have issues
Current worker fleet has override instance type but its a string. While auto_scaling_group supports a map for this. 

## I'm submitting a...
* [x ] feature request

## What is the current behavior?

Current worker fleet has override instance type but its a string. 

## What's the expected behavior?
Support a map of override instance types. Something like

launch_template_config {
    # ... other configuration ...

    override {
      instance_type     = "m4.xlarge"
      weighted_capacity = 1
    }

    override {
      instance_type     = "m4.2xlarge"
      weighted_capacity = 2
    }
  }

## Are you able to fix this problem and submit a PR? Link here if you have already.
No

**Comment by skang0601** [comment]
I had to just hardcoded just allowing one additional override instance type due to HCL limitations. You can't do counts on the inner configs and I could not see a way to support a list of overrides without something very complex.
Terraform 0.12 is suppose to add support for this with the dynamic blocks: https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each
so we'll likely have to wait till then.

For now the general advice has been to create the launch template outside of the module and reference it in.

**Comment by max-rocket-internet** [comment]
> For now the general advice has been to create the launch template outside of the module and reference it in.

Correct until we can find another way 🙂

**Comment by rverma-nikiai** [comment]
> For now the general advice has been to create the launch template outside of the module and reference it in.

@skang0601 Can you please share an example, I can not figure out how to pass launch template id. It seems asg has no input variable for that. If absence of that isn't it the case to fork and use custom template.

**Comment by max-rocket-internet** [comment]
> I can not figure out how to pass launch template id

Ah yes, you are correct. I thought we merged a PR for this but I think actually not.

PR for passing in launch template or launch configuration per worker group would be welcome 😃
