### ISSUE TITLE
Docs is not right

### ISSUE THREAD

**Issue by davidt-gh** [terraform-aws-modules/terraform-aws-eks#3136]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-20.0.md#upgrade-migrations

aws_auth_roles & aws_auth_users seem to be removed in 20.x, but in the examples the still show.

**Comment by bryantbiggs** [comment]
That is the migration guide, and it's correct

**Comment by davidt-gh** [comment]
But version 20.x does not have `aws_auth_roles` and it on green side of new method. Why is that, can you explain?

**Comment by bryantbiggs** [comment]
Re-read the guide please

**Comment by nkdicu** [comment]
The documentation is very unclear. I'm having the exact same issue as @davidt-gh

**Comment by mildmojo** [comment]
Not only confusing, the TF code shown in the v20 post-migration diff would fail if you tried to execute it, since it shows two modules declared with the same "eks" name. Example error:

```
 Error: Duplicate module call
│
│   on eks.tf line 12:
│  12: module "eks" {
│
│ A module call named "eks" was already defined at eks.tf:5,1-13. Module calls must have unique names within a module.
```

@bryantbiggs The module name error in the doc is part of what makes this confusing. You could've kindly pointed out that the diff shows `aws_auth_roles` and `aws_auth_users` getting split off into a completely different module with a different `source`.

### Problem

Readers need eagle eyes to spot the change in its current form; I had to re-read it several times and come find this ticket about it. Here's the important part of the current diff, adding a call to a new module _without removing the first one:_ 

```diff
 module "eks" {
   source  = "terraform-aws-modules/eks/aws"

...

+ module "eks" {
+   source  = "terraform-aws-modules/eks/aws//modules/aws-auth"
```

### Suggestions

Some things that would help clear this up for others:
- Please fix the syntax error by renaming the second `module "eks"` in the diff, e.g. `module "eks-aws-auth"`.
- Please amend the change description to avoid confusion for readers who aren't experts on the new module structure, e.g.:

```diff
-Since this sub-module is captured in the v20.x releases, users can continue using it even after the module moves forward with the next major version.
+Since this sub-module is captured in the v20.x releases, users can continue using `aws-auth` from v20.x even after the next major version no longer includes it.
```

**Comment by bryantbiggs** [comment]
that is merely a typo - not related to what this original issue is about
