### ISSUE TITLE
eks_managed_node_groups and auto mode issue

### ISSUE THREAD

**Issue by basoyan7** [terraform-aws-modules/terraform-aws-eks#3256]
## Description

When deploying an EKS cluster in auto mode using eks_managed_node_groups and the vpc-cni plugin under cluster_addons, the creation order is incorrect. The EKS cluster is created first, and then eks_managed_node_groups are attempted. However, for the node groups to function properly, the vpc-cni plugin in cluster_addons must be created before the node groups.

**Comment by brianpham** [comment]
@bryantbiggs Does this mean its working as expected? I thought Auto Mode supports running managed node groups in parallel

**Comment by gopkri24** [comment]
@bryantbiggs - @brianpham and me are in the same team and we're trying to create a cluster with auto mode and an eks managed node group, but the cluster fails to have healthy status as the nodes from managed node group cannot join the cluster. When digged deeper we found the addons were not installed. So would you please share an example config where we can create cluster with auto mode enabled and an eks managed node group, asking because we tried looking at the examples folder and couldn't find any

**Note**: In our configuration we are using default value for `bootstrap_self_managed_addons` and using `cluster_addons` for managing the addons.

**Comment by bryantbiggs** [comment]
> Note: In our configuration we are using default value for bootstrap_self_managed_addons and using cluster_addons for managing the addons.

Open an issue with a reproduction. We cannot troubleshoot issues that do not have reproductions
