### ISSUE TITLE
investigate adding create_before_destroy to worker asg to prevent downtime when recreating

### ISSUE THREAD

**Issue by ozbillwang** [terraform-aws-modules/terraform-aws-eks#35]
# I have issues

to change the instance type

## I'm submitting a

* [ ] bug report

## What is the current behavior

```
* module.eks.aws_launch_configuration.workers: 1 error(s) occurred:

* aws_launch_configuration.workers: Error creating launch configuration: AlreadyExists: Launch Configuration by this name already exists - A launch configuration already exists with the name eks-path-prod-0
	status code: 400, request id: xxx-xxx-xxx-xxx-xxx
```

## If this is a bug, how to reproduce? Please include a code sample

deploy EKS cluster, then change the instance type and apply again.

## What's the expected behavior

Should be no issue.

## Environment

* Affected module version: 1.0.0
* OS: Ubuntu
* Terraform version: 0.11.7

**Comment by brandoconnor** [comment]
Got it. I'll keep this ticket open to track the `create_before_destroy` thought. Thanks again for helping improve the module! 💯

**Comment by hobbsh** [comment]
I have tested out using `create_before_destroy` to transition between worker groups and it wont work gracefully unless there's a way to call a provisioner in the middle that does a `kubectl drain` on all the old workers.

**Comment by B-Hancock** [comment]
Any progress on this? I am recently going through the same issue.  Instead of changing the type, I just created a new set of worker nodes with the new type.  From there I can gracefully drain the old worker nodes before deleting them.  The only issue I am having now is that in order to delete the old worker set I need to modify the state file. To solve this the map would need to be based on keys, not on indexes.
