### ISSUE TITLE
Support for specifying worker AMIs other than the defaults

### ISSUE THREAD

**Issue by robertgates55** [terraform-aws-modules/terraform-aws-eks#540]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ x ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ~ ] kudos, thank you, warm fuzzy <<<<<<*Thank You!*

## What is the current behavior?
At the moment, the ami can be customised using the `worker_ami_name_filter_prefix` and `worker_ami_name_filter` vars. However the template is limited to the `owner = 602401143452`, and with a name format of `prefix-version-name`:
```
data "aws_ami" "eks_worker" {
  filter {
    name   = "name"
    values = ["${var.worker_ami_name_filter_prefix}-${var.cluster_version}-${var.worker_ami_name_filter}"]
  }

  most_recent = true

  # Owner ID of AWS EKS team
  owners = ["602401143452"]
}
```

I'd like to experiment with the ubuntu EKS images (https://cloud-images.ubuntu.com/aws-eks/) and so need to be able to override this. Happy to raise a PR, but not sure on policy on backwards compatibility. Would the easiest thing be to have a `var.worker_ami_id` that if specified overrides the existing options?

The ubuntu images are owned by `099720109477`, and have the format `ubuntu-eks/k8s_1.13/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190823.1`...

**Comment by max-rocket-internet** [comment]
Hey @robertgates55 
I tried this previously in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/127

The problem was that the Ubuntu AMI didn't use the same init process as the AWS AMI and was expecting to find CFN tags: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/127#issuecomment-420272542

Has that situation changed?

Either way, you can still just set whatever AMI you want per worker group, no PR required: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L25

**Comment by robertgates55** [comment]
I gave it a (brief) go - it looks like the bootstrap script is now in the same place, and accepts the same arguments, but iam-authenticator isnt installed. So perhaps putting that in the bootstrap template would be all that’s needed?

**Comment by max-rocket-internet** [comment]
You can just add what you need in `pre_userdata`: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L39
