### ISSUE TITLE
Ignore worker AMI version

### ISSUE THREAD

**Issue by nodesocket** [terraform-aws-modules/terraform-aws-eks#664]
Is it possible to ignore the worker AMI? I manually updated the version of Kubernetes in the AWS EKS UI control panel. I am still defining the worker AMI in Terraform with:

```
  worker_ami_name_filter = "v20190701"
```

This is now breaking with:

```
* module.k8s.data.aws_ami.eks_worker: data.aws_ami.eks_worker: Your query returned no results. Please change your search criteria and try again.
```

I'm guessing because the new version of Kubernetes I upgraded to is not available in that version `v20190701`. I cannot rebuild my worker node EC2 instances with the latest AMI. I simply want to just ignore the AMI filter.

**Comment by ankitabhopatkar13** [comment]
Hi

I faced the similar issue and the root cause of this occurs to be the changes made in data.tf file - 

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/c81e1d2fa75a2ddd50daa0bacac4548f6f4a18bb

Now instead of using filter as **v20190701** if you use **amazon-eks-node-${var.cluster_version}-v20190701** as your **worker_ami_name_filter** , it will solve your issue.

I think that the remaining part of variable should still be constructed in the module, as the default value is constructed. I will raise the PR for the same but for now this should solve your problem.

**Comment by nodesocket** [comment]
@ankitabhopatkar13 thanks for the reply.

I updated `  worker_ami_name_filter = "amazon-eks-node-1.14-v20190701"` but still getting:

```
* module.k8s.data.aws_ami.eks_worker: data.aws_ami.eks_worker: Your query returned no results. Please change your search criteria and try again.
```

**Comment by ankitabhopatkar13** [comment]
Hi @nodesocket,

Yes because `v20190701` doesn't exist for 1.14. It only exists for 1.13, 1.12, 1.11, 1.10.

So if you don't want your AMI to be upgraded to 1.14(which I would not recommend assuming your cluster is at 1.14), but to fix the issue you can check the current node's ami and which kubernetes version was it using and then use the same. Ex- 

`amazon-eks-node-1.13-v20190701`

**Comment by nodesocket** [comment]
@ankitabhopatkar13 that still did not work `amazon-eks-node-1.13-v20190701`. Confirmed the EC2 instances are running this AMI.

```
worker_ami_name_filter = "amazon-eks-node-1.13-v20190701"
```

On a related note, is there anything wrong or edge cases of running Kubernetes 1.14 on EKS, but the EC2 worker nodes running the 1.13 AMI?

**Comment by max-rocket-internet** [comment]
> is there anything wrong or edge cases of running Kubernetes 1.14 on EKS, but the EC2 worker nodes running the 1.13 AMI?

That's fine, details here: https://kubernetes.io/docs/setup/release/version-skew-policy/

But also note that `kube-proxy` doesn't update when you update the AMI:  https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Comment by nodesocket** [comment]
@ankitabhopatkar13 I am still having this issue, even when I changed the `worker_ami_name_filter` to match the current AMI for EKS version 1.14. Any ideas how I can work around this?

```
cluster_version = "1.14"
worker_ami_name_filter = "amazon-eks-node-1.14-v20200406"
```

**Comment by ankitabhopatkar13** [comment]
@nodesocket which version of terraform-aws-eks module are you using?

**Comment by nodesocket** [comment]
@ankitabhopatkar13 I was able to work around this by setting:

```
cluster_version = "1.14"
worker_ami_name_filter = "v20200406"
```

Which seemed to update the autoscaling group AMI, but it did no swap out my worker EC2 instances. Next time the EC2 worker instances need to be re-created should just use the new AMI.
