### ISSUE TITLE
Node group doesn't show up in the console

### ISSUE THREAD

**Issue by jmpsf** [terraform-aws-modules/terraform-aws-eks#683]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When I create the cluster with the terraform module, the nodes are created and registered in k8s (as stated by `kubectl get nodes`), but they don't show up at the EKS Console, so it seems there are no managed working nodes. 

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I've used the following terraform yaml.

```yaml
data "aws_eks_cluster" "internal" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "internal" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.internal.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.internal.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.internal.token
  load_config_file       = false
  version                = "~> 1.9"
}

module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  cluster_name                    = "internal-cluster"
  cluster_version                 = "1.14"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  subnets = [
    REDACTED,
    REDACTED,
    REDACTED
  ]
  vpc_id = REDACTED

  map_users = var.map_users

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 3
    }
  ]
}
```

## What's the expected behavior?

Nodes should appear in the EKS AWS Console under Node Groups

## Environment details

* Affected module version: 8.0.0
* OS: Debian Buster
* Terraform version:
```
Terraform v0.12.13
+ provider.aws v2.44.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

**Comment by dpiddockcmp** [comment]
Hi @jmpsf 

You haven't created an EKS Node Group. You've directly created a classic ASG with Launch Configurations that needs manual maintenance.

If you want to create node groups you need to use `node_groups` variable instead of `worker_groups`:
```
module "eks" {
  # ....
  # Don't set "worker_groups"
  node_groups = {
    default = {
      instance_type = "m4.large"
      max_capacity  = 3
    }
  }
}
```

See the [managed_node_groups example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/b70a82887717eee856b0873e0561a1328c0e7b7a/examples/managed_node_groups/main.tf) and [node_groups submodule](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/b70a82887717eee856b0873e0561a1328c0e7b7a/modules/node_groups) for more documentation.

**Comment by jmpsf** [comment]
Oh... sorry @dpiddockcmp I was tired and I guess I didn't correctly read the docs.

Thank you :)
