### ISSUE TITLE
Cannot import existing kubernetes object into terraform state when migrating from 7.x to 8.x or greater

### ISSUE THREAD

**Issue by nothingofuse** [terraform-aws-modules/terraform-aws-eks#785]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When migrating from version 7.x (with manage_aws_auth = true) to version 8.x or higher of the module, i am unable to import the aws-auth configmap whether it is being managed by the module or not.
I have also opened a bug with the kubernetes provider: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/793

## If this is a bug, how to reproduce? Please include a code sample if relevant.

1. `terraform init`
2. `terraform import kubernetes_config_map.aws_auth kube-system/aws-auth`

## What's the expected behavior?

the resource should be imported without issue

## Are you able to fix this problem and submit a PR? Link here if you have already.
no

## Environment details

* Affected module version: 8.x and greater (tested on 8.0.1, 9.0.0, 10.0.0)
* OS:
* Terraform version: 0.12.19

**Comment by nothingofuse** [comment]
If i set host to a static value in the provider config, it properly points to the correct host on import, so it seems that the providers configuration is not being properly loaded when using data elements?

```
provider "kubernetes" {
  host = "https://NSADJLASFOEKEA.gr7.us-east-1.eks.amazonaws.com"
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "1.11.1"
}
```
```
Error: Get https://NSADJLASFOEKEA.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth: x509: certificate signed by unknown authority
```

**Comment by dpiddockcmp** [comment]
I've had trouble getting the kubernetes provider to play nicely with import too in the past. Try temporarily setting `load_config_file = true` and `config_path` to the location of the generated kube config file.

**Comment by Ghazgkull** [comment]
If I understand correctly, the upshot here is that anyone with a module-managed aws-auth config is currently blocked from upgrading from version <=7 to version >=8.

I believe this is because the module internally changed from using a null_resource to a kubernetes-provider resource, but the module itself doesn't handle fixing the terraform state to handle that change. Manual migration instructions are provided for clients, but those instructions don't work because the kubernetes-provider fails to import the aws-auth configmap. Does that sound like where we're at?

**Comment by barryib** [comment]
From terraform-aws-eks 7.0.0, we use the kubernetes provider instead of kubectl to manage aws-auth confgmap. So you have to import it.

To do so, you have to use a local kubeconfig for authentication (as @dpiddockcmp suggested), because you can't use variable and data source during [terraform import](https://www.terraform.io/docs/commands/import.html#provider-configuration)
> The only limitation Terraform has when reading the configuration files is that the import provider configurations must not depend on non-variable inputs. For example, a provider configuration cannot depend on a data source.

Here how I did it https://github.com/terraform-aws-modules/terraform-aws-eks/pull/355#issuecomment-535962593

I think we should add more precise doc/exemple for aws-config import. Working on something else right now, but If someone could do that it would be great.

**Comment by rastakajakwanna** [comment]
My 5 cents how to fix it: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/699#issuecomment-600729809

**Comment by aholbreich** [comment]
I've two clusters in one terraform repostiory created with version 7.0.0 and  8.1.0
but not to update first to any >8.0.0 i end up with two kubernetes providers - which is not allowed? How to deal with it?

**Comment by dpiddockcmp** [comment]
You can define multiple provider blocks with aliases. Then pass in the aliased provider to your module. See the [Terraform documentation](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances) for more
