### ISSUE TITLE
iam_instance_profile for workers is linked to worker group definition

### ISSUE THREAD

**Issue by cmrust** [terraform-aws-modules/terraform-aws-eks#794]
It appears the module will not create the instance profile for the workers role, unless a workers_group is defined.

In my case, I'm using a third party tool, spotinst.com, to manage autoscaling worker nodes for my EKS cluster. So, there's no need for me to define a workers_group within the module, but I still need this instance profile defined.

It appears to be the use of `local.worker_group_count` here that's causing my issue:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L323

I've been looking at this for a while, considering creating a PR, but I'm not sure there's a safe way to go about it without a breaking change. Any suggestions are welcome.

Creating a stub workers_group stanza with `asg_max_size = 0` results in:
```
Error: Error creating AutoScaling Group: ValidationError: Max bound, 0, must be greater than or equal to min bound, 1
```

Thanks

**Comment by dpiddockcmp** [comment]
Yes, for some reason an instance profile is created for each defined group. I'm not quite sure why that design decision was made back in the beginning instead of a one-to-one mapping with the role 🤷‍♂ . Switching to a single instance role would be a breaking change for everybody using launch templates and config based workers handled by the module

I think there are two easy options for you here:
- carry on like you were with creating a zero sized ASG. You'll need to set `asg_min_size = 0` and `asg_desired_capacity = 0` too.
- create the instance profile yourself. You then don't end up with the unnecessary ASG and associated resources. Something like:
```hcl
resource "aws_iam_instance_profile" "profile" {
  name = module.eks.worker_iam_role_name
  role = module.eks.worker_iam_role_name
}
```

**Comment by cmrust** [comment]
Worked around this by creating the instance_profile on my own:

```
resource "aws_iam_instance_profile" "cluster_instance_profile" {
  name_prefix = local.cluster_name
  role = module.eks.worker_iam_role_name
}
```

Closing this issue.
