### ISSUE TITLE
When re-creating a cluster from scratch, aws_auth.tf somehow tries the previous-run's EKS API endpoint

### ISSUE THREAD

**Issue by christopher-demarco** [terraform-aws-modules/terraform-aws-eks#830]
# I have issues

## I'm submitting a...

* [X] bug report

## What is the current behavior?
Create a cluster, it fails:

```
Error: Post https://ENDPOINT-REDACTED-1.yl4.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps: dial tcp: lookup ENDPOINT-REDACTE-1.yl4.us-west-2.eks.amazonaws.com on 8.8.8.8:53: no such host

  on .terraform/modules/cluster/terraform-aws-eks-11.0.0/aws_auth.tf line 61, in resource "kubernetes_config_map" "aws_auth":
  61: resource "kubernetes_config_map" "aws_auth" {

```

That endpoint is the endpoint of the previous (n-1th) run.

After destroying all resources, tfstate is clean as expected. No residual state in the `.terraform/module` directory—where is that stale reference coming from?!

Re-running will succeed, so it's clearly an issue with resource-ordering or cache?

Issue is in both v8.2.0 and v11.0.0 .

## Environment details

* Affected module version: 8.2.0, 11.0.0
* OS: macOS
* Terraform version: 0.12.23

**Comment by christopher-demarco** [comment]
We fixed this, but it might bear updating documentation: Adding a `kubernetes` provider using the module-built EKS endpoint fixes this behavior. Apparently the various `kubernetes_*` resources here were using the local `$KUBECONFIG`, which wasn't yet updated.

This situation is potentially bad: if `$KUBECONFIG` points to an accessible cluster, then the `aws-auth` configmap could be unexpectedly updated.

**Comment by barryib** [comment]
I don't get your point. Do you mean that the [example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf#L26-L40) and/or [readme](https://github.com/terraform-aws-modules/terraform-aws-eks#usage-example) are not working ?

**Comment by naveenb30** [comment]
I'm also experiencing same issue, any solution for this ?

**Comment by mitchelladam** [comment]
I'm having this issue as well, explicitly when i'm trying to create 2 eks clusters in the same vpc.
this happens in from-scratch as soon as it reaches the aws_auth kubernetes_config_map

because i'm creating two eks clusters, i have two aliased kubernetes providers. using them works fine and the config for them is created correctly,.
However the kubernetes config map in both modules doesn't use either of the configurations that i've just created and instead uses the default local kubernetes and whatever context i've currently got it set to. there doesn't seem to be any way of getting it to use the correct configuration either.

i've attached an example where this occurs.

[main.tf.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/5157637/main.tf.txt)

**Comment by dpiddockcmp** [comment]
@mitchelladam You also need to pass the aliased kubernetes provider to the module. Otherwise Terraform will use a zero-config provider which defaults to whatever `$KUBECONFIG` or `~/.kube/config` points to.

```hcl
module "eks" {
  # ....
  providers {
    kubernetes = kubernetes.clusterA
  }
}
```
More details in the docs [here](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly)

**Comment by shankar96** [comment]
@dpiddockcmp what is clusterA ? can u show some examples. i am facing this frequent issue while recreation of cluster after destroying.

**Comment by mitchelladam** [comment]
@shankar96 it's from my example main.tf in my comment
@dpiddockcmp that did work, thanks for the quick response

**Comment by shankar96** [comment]
@mitchelladam can u share working main.tf 
I am getting  follwing errors

```
quotes surrounding this reference to silence this warning.

Error: Unsupported block type

  on eks.tf line 116, in module "eks":
 116:   providers {

Blocks of type "providers" are not expected here.
```

**Comment by mitchelladam** [comment]
@shankar96
just missing the = sign 
providers = {

**Comment by shankar96** [comment]
did that
thanks 
```
module "eks" {
  # ....
  providers {
    kubernetes = kubernetes.clusterA
  }
}
```

**Comment by barryib** [comment]
Closing, since this sounds like you fixed you issue. Feel free to re-open it if you don't.
