### ISSUE TITLE
With latest releases of module, is the AWS account/IAM user creating the cluster no longer authorized by default?

### ISSUE THREAD

**Issue by mojochao** [terraform-aws-modules/terraform-aws-eks#832]
I used a much earlier version of this module with success, but thought I'd check out the latest and greatest, especially the managed node groups.

Previously, after creating the cluster setting my AWS profile to the one used to create the cluster, and setting my KUBECONFIG to the one created by the module, I could run a `kubectl cluster-info` and get results as expected.  After building a cluster with the latest version of the module with the managed node groups example, I get the error `You must be logged in to the server (Unauthorized)`.

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

After creating an EKS cluster with managed node groups, I cannot access the API.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I highly doubt it's a bug, as I'm sure it's config related.  What I did was:
* created an instance of the module according to this example https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/managed_node_groups
* did not explicitly pass `map_accounts`, `map_users` or `map_roles` vars, as I didn't have to with earlier versions of this module

## What's the expected behavior?

I expected to get a valid response back from `kubectl cluster-info` after setting `AWS_PROFILE` and `KUBECONFIG` in the environment with the AWS profile used to create the cluster and the generated kubeconfig file

Is this expectation no longer valid?  Do we have to explicitly add the IAM user to the `aws-auth` configmap now?  Are there examples of this documented?

## Are you able to fix this problem and submit a PR? Link here if you have already.

No.  This is more of a proper usage issue.

## Environment details

* Affected module version: v11.0.0
* OS: macOS Catalina v10.15.4
* Terraform version: v0.12.24

## Any other relevant info

Thanks in advance for any answers you may have.

**Comment by dpiddockcmp** [comment]
Nothing has changed in the form of access to the cluster. The module now uses kubernetes provider instead of a call out to kubectl so configuration errors in the generated kubeconfig won't be noticed.

The creating IAM user or role is still granted forever access to the cluster. It's an internal EKS implementation detail that can't be changed, yet.

Cluster must be created by an IAM user or role, not the root account. Otherwise no access will be granted.

If you are using a profile to access the IAM user/role then the profile must also be specified in the user block in the kubeconfig. You can add this to the module's generated kubeconfig via the `kubeconfig_aws_authenticator_env_variables` variable. Example:
```hcl
module "eks" {
  # ... normal stuff
  kubeconfig_aws_authenticator_env_variables = {
    "AWS_PROFILE" = "my-profile"
  }
}
```

**Comment by mojochao** [comment]
The missing kubeconfig config was indeed the culprit. Thanks for the assistance!
