### ISSUE TITLE
Supports Service-Linked Roles

### ISSUE THREAD

**Issue by abdennour** [terraform-aws-modules/terraform-aws-eks#839]
## I'm submitting a...

* [x] feature request
* [ ] support request 
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

Is there a plan in the roadmap to support [Supports Service-Linked Roles](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-eks-supports-service-linked-roles/)

**Comment by dpiddockcmp** [comment]
No changes are needed to the module to "support" service-linked roles. The EKS service just adds them to your account when creating new clusters as necessary. New clusters no longer need to attach the `AmazonEKSServicePolicy` policy to the cluster IAM role.

Unfortunately neither the documentation or announcement specify what the change means for *existing* clusters. Can the policy be removed from the cluster IAM role without causes issues? Will that break upgrades of clusters in the future? Could the master plane mysteriously break because it suddenly doesn't have permissions to recreate/modify the ENI?

Safest option for the module right now is to do nothing. And maybe contact the container team for clarification in their documentation for existing clusters.

User creating the cluster needs permissions to create service linked roles, as per the more [generic documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#service-linked-role-permissions)
