### ISSUE TITLE
Changing tags causes node groups to be replaced.

### ISSUE THREAD

**Issue by blongman-snapdocs** [terraform-aws-modules/terraform-aws-eks#843]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When I change the values of tags, a plan shows that all node groups need to be replaced:

```
 (feature/DEVOPS-586/recreate-east-cluster-but-better) $ terraform plan -no-color | grep "must be replaced"
  # module.eks.local_file.kubeconfig[0] must be replaced
  # module.eks.module.node_groups.aws_eks_node_group.workers["jobs"] must be replaced
  # module.eks.module.node_groups.aws_eks_node_group.workers["web"] must be replaced
  # module.eks.module.node_groups.random_pet.node_groups["jobs"] must be replaced
  # module.eks.module.node_groups.random_pet.node_groups["web"] must be replaced
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a cluster with node groups, and then change a base level tag.

## What's the expected behavior?

Tags are updated in place.

## Are you able to fix this problem and submit a PR? Link here if you have already.

No.

## Environment details

* Affected module version: 11.0.0
* OS: OS-X 10.14.6
* Terraform version: 0.12.10

**Comment by dpiddockcmp** [comment]
Yes, this is unfortunate behaviour with how everything was stitched together to ensure dependency ordering in the one-shot module.

From my understanding of how Terraform works, this is roughly the reason behind why things gets recreated:
- The `aws_eks_cluster` resource is now in an unknown state at refresh time due to pending changes
- One of the `null_data_source.node_groups` data source's inputs is now "unknown" and so it can't be refreshed at "refresh" time. The refresh is delayed until apply time. Its outputs are now "unknown". This data source is required to enforce dependency between the `eks_node_group` and other required resources
- `node_groups.random_pet.node_groups` has an unknown input, so is tagged for updating
- `node_groups.aws_eks_node_group.workers` thus get tagged for recreation as its name will be changed

I don't think there's much we can do design-wise in the module to work around this particular issue at this time. Terraform 0.13 is scheduled to get a bunch of dependency improvements around modules: https://github.com/hashicorp/terraform/issues/17101 . `depends_on` against variables would be the magic feature.

Work arounds:
- You can avoid the recreation of the `eks_node_group` by using targetted apply. e.g. `terraform plan -target=module.eks.aws_eks_cluster.this`
- Maybe running with refresh turned off would work around the data source unknown issue? `terraform plan -refresh=false`
- A bigger change: have the node_groups in a different configuration. There's half support for using the module stand alone but it should be improved.

**Comment by blongman-snapdocs** [comment]
Thanks for getting back to me on this.  The tags aren't an giant issue for me quite yet, but if they become so (like we actually start tacking expenses to tags), it looks like I could remove the node group statements from the module input and define one or more aws_eks_node_groups separately, and import the existing node groups in to them.

**Comment by barryib** [comment]
After some tests, I ended up with this possible fix https://github.com/terraform-aws-modules/terraform-aws-eks/pull/868.
