### ISSUE TITLE
EKS secondary ip address support for the pods

### ISSUE THREAD

**Issue by cyperplex** [terraform-aws-modules/terraform-aws-eks#870]
Does the current version of the module support secondary EKS ip address support for the pods . 

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

**Comment by dpiddockcmp** [comment]
Hi. Thanks for your issue.

Do you have a link to some AWS documentation to expand on this request? How would this be relevant to the configuration of the EKS resources? I don't understand what you're asking for.

**Comment by cyperplex** [comment]
Hi,

Sorry, these are the two reference docs. 

https://eksworkshop.com/beginner/160_advanced-networking/secondary_cidr/
https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/

The core issue is within the EKS clusters were provisioning via the TF module, the subnets are shared between the nodes and the pods. AWS announced the support of "secondary ip address subnets" which would allow the provisioning of subnets that are local to the VPC  that the pods could use to avoid using the "main" subnet, for pod to pod communication.

**Comment by dpiddockcmp** [comment]
Those links are talking about two different things. Neither of which require any changes to this module.

> https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/

This announcement gives you more IP ranges to choose from when creating a VPC for use with EKS. Instead of the old faithfuls from RFC 1918.

> https://eksworkshop.com/beginner/160_advanced-networking/secondary_cidr/

I've flicked through this and a lot of it is out of scope for the module:
- this module doesn't create VPC resources. You need to use something else like the [terraform-aws-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc/) module which supports secondary CIDR ranges.
- the module does not configure the CNI daemonset. You need to handle that outside. It would be really difficult to do in the module as the kubernetes provider cannot forcefully override or adopt existing resources
- terraform kubernetes provider does not support CRD resources so it's impossible to configure those here or it involves a lot of gymnastics
- you can only annotate nodes after they have joined to the cluster. The CNI also supports using a label. You can set that with the `kubelet_extra_args` key in workers maps. See the `spot_instances` example for how to do it.

Careful when adding new subnets to your VPC. The `eks_cluster` resource cannot change subnet allocations and Terraform will attempt to recreate it. If you are expanding an existing cluster then ensure that the top level `subnets` list does not change. Worker groups can have their subnet allocations changed independently via the `subnets` key in the various workers maps: `workers_group_defaults`, `worker_groups`, `worker_groups_launch_template`.

**Comment by cyperplex** [comment]
dpiddockcmp,

Thank you so much for taking the time to go into so much  detail, and thanks for sending me the right direction, Ill checking the module you referenced and test to try ensure that terraform doesnt try delete the networks. 

Cheers
