### ISSUE TITLE
[Request] Support fixed names for ASG resources (all resources in general)

### ISSUE THREAD

**Issue by debjitk** [terraform-aws-modules/terraform-aws-eks#896]
Instead of using `name_prefix` why not use `name` in `aws_autoscaling_group` `workers_launch_template` as i see no advantage in using `name_prefix` instead of `name`

Also can we prefix launch templates with `lt` and auto scaling groups with `asg`. Not important but would be nice naming convention.

```
resource "aws_autoscaling_group" "workers_launch_template" {
  ...
  name = join("-", compact([
        "asg",
        aws_eks_cluster.this[0].name,
        lookup(var.worker_groups_launch_template[count.index], "name", count.index),
        lookup(var.worker_groups_launch_template[count.index], "asg_recreate_on_change", local.workers_group_defaults["asg_recreate_on_change"]) ? random_pet.workers_launch_template[count.index].id : ""
      ]
    )
  )
  ...
}
```

**Comment by max-rocket-internet** [comment]
> Instead of using name_prefix why not use name in aws_autoscaling_group

There's no specific reason for this that I know of, it's simply historical. I also don't like it as you end up with resources named things like `my-worker-group120190507160153996400000008`. 

The problem is changing this without impacting existing users ability to update to newer versions of the module. One idea would be to stop using `name_prefix` and then users would have to:
- Set the name of their workergroup manually to `my-worker-group120190507160153996400000008`
- Massage the TF state to deal with this change

**Comment by daroga0002** [comment]
In general if we take a look in bigger scale where modules should be always reusable, then `name_prefix` is the only option. 

Lets assume you have a dozen of clusters deployed then you must manage each name somehow as autoscaling group in AWS:
`Must be unique to this account in the current Region and no more than 255 characters.`

**Comment by jverce** [comment]
> In general if we take a look in bigger scale where modules should be always reusable, then `name_prefix` is the only option.
> 
> Lets assume you have a dozen of clusters deployed then you must manage each name somehow as autoscaling group in AWS:
> `Must be unique to this account in the current Region and no more than 255 characters.`

How would allowing users the option to provide either the `name` or the `name_prefix` limit the reusability of the module?
If anything, adding this option would involve putting the responsibility on the user in terms of figuring out the naming schema and implementing its logic, requiring some effort on their end (which is OK because it was their decision in the first place) but it doesn't prevent reusability AFAICT. Whatever the module is doing in terms of deciding the final name it can also be done by the user, right?

Having the option to provide the `name` of a resource is extremely useful when importing resources to the Terraform state that do not comply with the [prefix/suffix format requirements defined by the AWS provider](https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/internal/naming/naming.go#L41-L71). Without the ability to provide the `name` directly it's virtually impossible to import an existing EKS cluster into this module transparently.
