### ISSUE TITLE
Issue with Codebuild timeouts after repeating module.eks.null_resource.wait_for_cluster[0]: Still creating

### ISSUE THREAD

**Issue by trey2001** [terraform-aws-modules/terraform-aws-eks#919]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Running eks module in codebuild and getting a repeat of this until an hour later and codebuild times out: module.eks.null_resource.wait_for_cluster[0]: Still creating... [1m0s elapsed]·[0m·[0m]

This happens after successfully creating the egress "module.eks.aws_security_group_rule.workers_egress_internet"

This was after the successful creation of the cluster as I see it in EKS.
module.eks.aws_eks_cluster.this[0]: Creation complete after 11m47s

I have set this in my eks module:
  wait_for_cluster_cmd              = "until curl -k -s $ENDPOINT/healthz >/dev/null; do sleep 4; done"

Didn't seem to make a difference. I can't tell how it is getting stuck or on what. The trace logs don't seem to lead me to any good solution. 

## What's the expected behavior?
To not spin on waiting.

## Environment details
Codebuild AWS Linux
* Affected module version:
* OS: linux
* Terraform version: .12

**Comment by dpiddockcmp** [comment]
Terraform needs to be able to communicate with the cluster in order to create the aws-auth ConfigMap. So this is probably a networking issue.

I haven't used CodeBuild.

Is your build environment allowing outgoing internet connections? You need to have `cluster_endpoint_public_access = true` (default).

Or does your build have internal access to the VPC where you created the cluster if you have `cluster_endpoint_public_access = false` and `cluster_endpoint_private_access = true`?

You can stop the module from attempting to create the configmap with `manage_aws_auth  = false` but then you must create it yourself before worker nodes will be able to join the cluster.

**Comment by trey2001** [comment]
Thanks I believe I got past that issue, but when running I still dont get the worker nodes registered in my node group just an empty cluster. My codebuild log shows a creation of an AWS auth config:
[awsauth.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/4782551/awsauth.txt)

My worker config in my cluster looks like this:
    worker_groups = [
    {
      name          = "workers"
      instance_type = "t3.small"
      asg_max_size  = 2
      additional_security_group_ids = ["sg-0bd04c3bd332225aaa"]
      iam_instance_profile_name     = "NodeInstanceRole"
      kubelet_extra_args  = "--node-labels=node.kubernetes.io/lifecycle=normal"
    }
  ]
}

**Comment by trey2001** [comment]
Sorry fory lack of understanding on the topic still a bit new to EKS. I believe I use worker nodes self managed by using the worker nodes setup above. Correct? Otherwise I could create my own managed node group module. Thanks for the help.
