### ISSUE TITLE
Unauthorized error when upgrading Kubernetes version

### ISSUE THREAD

**Issue by mcavoyk** [terraform-aws-modules/terraform-aws-eks#923]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

An update of EKS Kubernetes version and `aws-auth` configmap together cause an error on Terraform apply. 

```hcl
 Error: Failed to update Config Map: Unauthorized
   on .terraform/modules/eks/terraform-aws-eks-12.1.0/aws_auth.tf line 64, in resource "kubernetes_config_map" "aws_auth":
   64: resource "kubernetes_config_map" "aws_auth" {
```

Re-run of terraform apply works without issue.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Update Kubernetes version of control plane (in this case, 1.14 -> 1.15) and add a role to the aws-auth configmap.

## What's the expected behavior?

Terraform apply is successful. My estimate would be the `wait_for_cluster` null resource needs a trigger on Kubernetes version to handle waiting on Kubernetes cluster upgrade as well on creation.

## Are you able to fix this problem and submit a PR? Link here if you have already.

N/A

## Environment details

* Affected module version: 12.1.0
* OS: linux
* Terraform version: 0.12.25

**Comment by dpiddockcmp** [comment]
Your access token expired in the 30 to 40 minutes it usually takes for a cluster to upgrade.

In a fully configured setup the data source that fetches the IAM token does so at the start of the process.
The IAM token generated for accessing clusters is only valid for 15 minutes.
This is not user configurable.
Terraform performs the ConfigMap change after upgrading the cluster due to the dependency chain.

Rerun your Terraform and everything should finish applying.

In future I would recommend that you perform upgrading of the cluster as an independent stage.

Unfortunately I don't think there's anything we can do in the module to work around this particular situation.

**Comment by mcavoyk** [comment]
That makes a lot of sense. Thanks for the quick reply.

**Comment by amitsehgal** [comment]
it happens to me too.....

**Comment by kaykhancheckpoint** [comment]
I'm having this problem now, how did you guys fix it?

**Comment by maineffort** [comment]
Same here:
`Error: Failed to update Config Map: Unauthorized
  on aws_auth.tf line 1, in resource "kubernetes_config_map" "aws_auth":
   1: resource "kubernetes_config_map" "aws_auth" {
Error: error waiting for EKS Node Group (my-eks:my-eks-node-group) creation: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 20m0s)
  on eks.tf line 127, in resource "aws_eks_node_group" "my-eks-node":`
