### ISSUE TITLE
Support for the new amazon-eks-node-* AMI with bootstrap script

### ISSUE THREAD

**Issue by erks** [terraform-aws-modules/terraform-aws-eks#97]
# I have issues

The [new amazon-eks-node-* AMI with bootstrap script](https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md#amazon-eks-node-v23) has been released. However, it's not backward compatible with the old AMI and doesn't work with this module.

https://aws.amazon.com/blogs/opensource/improvements-eks-worker-node-provisioning/

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

This module only works with the `eks-woker-*` AMIs.

## If this is a bug, how to reproduce? Please include a code sample if relevvant.

N/A

## What's the expected behavior?

This module should also work with the new `amazon-eks-node-*` AMI. The entire `userdata.sh.tpl` can be reduced to something like this:

```bash
# Allow user supplied pre userdata code
${pre_userdata}

# Bootstrap and join the cluster
/etc/eks/bootstrap.sh --b64-cluster-ca '${cluster_auth_base64}' --apiserver-endpoint '${endpoint}' --kubelet-extra-args '${kubelet_extra_args}' '${cluster_name}'

# Allow user supplied userdata code
${additional_userdata}
```

## Are you able to fix this problem and submit a PR? Link here if you have already. 

I can contribute, but would like to discuss on how we want to approach backward compatibility first.

## Environment details

* Affected module version: 1.4.0
* OS: all
* Terraform version: all

## Any other relevant info

See:
* https://github.com/awslabs/amazon-eks-ami/pull/16 for more info of the change.
* https://aws.amazon.com/blogs/opensource/improvements-eks-worker-node-provisioning/

**Comment by max-rocket-internet** [comment]
Thanks for the issue!

> would like to discuss on how we want to approach backward compatibility first

Great question. The problem is now that [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L21) we are using the latest AMI that starts with `eks-worker-`. So currently, this new AMI would be released, on `terraform apply` the ASG would get a new LC with this new AMI but the user-data would be incompatible. This is a problem.

I propose we pin the AMI name string now to `eks-worker-v22`. This solves that problem for people using the latest version of this module. People using older versions will have a problem unfortunately.

Then we just create a new release of this module where we change both the user-data and the AMI name string together.

Does that make sense?

**Comment by max-rocket-internet** [comment]
Ahh, actually, from the release notes, the new AMI name is `amazon-eks-node-v23` so there is no problem for now.

So I think just make a PR to change the user-data and the AMI name filter to `amazon-eks-node-*` and that's it?
