### ISSUE TITLE
Private subnet vs all subnet ?

### ISSUE THREAD

**Issue by ArchiFleKs** [terraform-aws-modules/terraform-aws-eks#975]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [X] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [X] kudos, thank you, warm fuzzy

Should we put all subnet in the example and not just private subnet ? And what would the impact be ?

From the docs it is not very clear what is the impact of putting only private or only public subnet is the subnet option when creation a cluster except that it adds automaticly the "shared" tag.

I've always been able to create internal and external loadbalancer with the right tag on the public subnet even if the cluster module specify only private subnet as per the basic example: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf#L128

Would it be simpler to put private and public subnet all together ?

**Comment by dpiddockcmp** [comment]
The `var.subnets` list given to the `aws_eks_cluster` is used by the eks service to decide where to create the ENIs for the cluster and nodes to communicate without going over the "public" AWS internet. It will create one ENI per AZ picking from the subnets given. Not sure what algorithm they use to pick which subnet to use in each AZ. I think there's also a limit of 2 or 3 ENIs in total?

The EKS service also adds tags to those subnets, as you've observed. The tags are to help the kubernetes cluster to decide where to place load balancers when you create a LoadBalancer type Service. More details about how that works in an old issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/274#issuecomment-470062660

Plus the `var.subnets` is, by default, the list used for all the worker nodes. You can override in `var.workers_group_defaults[subnets]` or on an individual worker group basis.

I would highly recommend that you configure it so that workers are only created in private subnets unless you have a really valid reason for public worker nodes.
