### ISSUE TITLE
Should we manage k8s resources with this module?

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-aws-modules/terraform-aws-eks#99]
This is a general question about the direction of this module.

We get requests that would require this module to manage or create Kubernetes resources. Some examples:

- Modifying CNI configuration before worker ASG creation: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/96
- Deploying cluster autoscaler: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/71
- Manage add-ons: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/19

I think we should have a clear position on this types of issues.

**Comment by brandoconnor** [comment]
^ we're on the same page here. 100% we should avoid adding bits of shell script, here, there, and everywhere to accommodate individual needs because those would stretch a mile long. Providing adequate facilities for others to flexibly add what they'd want on top of what we have (e.g. `pre-userdata` and `post-userdata`) is a better approach and I'm all ears for those sorts of additions. I think what we have will more than likely be flexible enough for the long haul but perhaps you see room for improvement.

I'm a bit more torn if the kubernetes provider gets to the point of useful in conjunction with this module. When/if that happens, I'd at least be interested to see how people would want to use that within the module. My inclination is that most if not all of this would be better suited for a separate state and as a consumer of the module rather than within it, but I'm reserving the chance that some is worth integrating.

Curious to hear any other thoughts you might have. If we're seeing eye to eye on most or all of the above, let's close this out.

**Comment by max-rocket-internet** [comment]
OK cool, I think we are definitely on the same page about this! That's great.

> Providing adequate facilities for others to flexibly add what they'd want on top of what we have (e.g. pre-userdata and post-userdata) is a better approach and I'm all ears for those sorts of additions.

:100:

> I'm a bit more torn if the kubernetes provider gets to the point of useful in conjunction with this module. 

Perhaps later but for now I think it's a little tricky due to providers not supporting any sort of [depends_on](https://github.com/hashicorp/terraform/issues/2430) functionality. We had this when trying to create DBs inside an RDS instance using the PostgreSQL terraform provider.

> My inclination is that most if not all of this would be better suited for a separate state

Agreed.

Anyway, for now I'll close this and we can refer to this for future issues. And if it changes in the future then we can re-evaluate the situation.

**Comment by rodlogic** [comment]
> Perhaps later but for now I think it's a little tricky due to providers not supporting any sort of [depends_on](https://github.com/hashicorp/terraform/issues/2430) functionality. We had this when trying to create DBs inside an RDS instance using the PostgreSQL terraform provider.

@max-rocket-internet I think this is precisely why I came here to enter a question-issue: it is possible to provision the ALB Ingress Controller within the same Terraform apply?

So the answer is no: we can't setup a Kubernetes provider with the outputs of an EKS cluster created by this terraform module and the main limination seems to be https://github.com/hashicorp/terraform/issues/2430

**Comment by max-rocket-internet** [comment]
Correct. Not possible in a single apply.
